using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class AazFile
    {
        public string Aaz00 { get; set; }
        public string Aaz01 { get; set; }
        public string Aaz02 { get; set; }
        public string Aaz03 { get; set; }
        public string Aaz04 { get; set; }
        public string Aaz05 { get; set; }
        public string Aaz06 { get; set; }
        public string Aaz07 { get; set; }
        public string Aaz08 { get; set; }
        public string Aaz09 { get; set; }
        public short? Aaz21 { get; set; }
        public string Aaz211 { get; set; }
        public string Aaz212 { get; set; }
        public short? Aaz22 { get; set; }
        public string Aaz221 { get; set; }
        public string Aaz222 { get; set; }
        public short? Aaz23 { get; set; }
        public string Aaz231 { get; set; }
        public string Aaz232 { get; set; }
        public short? Aaz24 { get; set; }
        public string Aaz241 { get; set; }
        public string Aaz242 { get; set; }
        public short? Aaz25 { get; set; }
        public string Aaz251 { get; set; }
        public string Aaz252 { get; set; }
        public short? Aaz26 { get; set; }
        public string Aaz31 { get; set; }
        public string Aaz32 { get; set; }
        public string Aaz33 { get; set; }
        public short? Aaz41 { get; set; }
        public short? Aaz42 { get; set; }
        public string Aaz431 { get; set; }
        public string Aaz432 { get; set; }
        public string Aaz441 { get; set; }
        public string Aaz442 { get; set; }
        public string Aaz51 { get; set; }
        public short? Aaz61 { get; set; }
        public short? Aaz62 { get; set; }
        public short? Aaz63 { get; set; }
        public string Aaz64 { get; set; }
        public string Aaz65 { get; set; }
        public string Aaz66 { get; set; }
        public string Aaz67 { get; set; }
        public string Aaz68 { get; set; }
        public string Aaz69 { get; set; }
        public string Aaz70 { get; set; }
        public string Aaz71 { get; set; }
        public string Aaz72 { get; set; }
        public string Aaz73 { get; set; }
        public string Aaz74 { get; set; }
        public string Aaz75 { get; set; }
        public string Aaz76 { get; set; }
        public string Aaz77 { get; set; }
        public string Aaz78 { get; set; }
        public string Aaz79 { get; set; }
        public string Aaz80 { get; set; }
        public string Aaz81 { get; set; }
        public string Aaz82 { get; set; }
        public string Aaz83 { get; set; }
        public string Aaz84 { get; set; }
        public string Aaz85 { get; set; }
        public string Aaz86 { get; set; }
        public string Aaz87 { get; set; }
        public short? Aaz88 { get; set; }
        public string Aaz89 { get; set; }
        public string Aaz90 { get; set; }
        public string Aaz91 { get; set; }
        public string Aaz92 { get; set; }
        public string Aaz93 { get; set; }
        public string Aaz94 { get; set; }
        public string Aaz95 { get; set; }
        public string Aaz96 { get; set; }
        public string Aaz97 { get; set; }
        public string Aaz98 { get; set; }
        public string Aaz99 { get; set; }
        public string Aaz100 { get; set; }
        public string Aaz101 { get; set; }
        public string Aaz102 { get; set; }
        public string Aaz103 { get; set; }
        public string Aaz104 { get; set; }
        public string Aaz105 { get; set; }
        public string Aaz106 { get; set; }
        public string Aaz107 { get; set; }
        public string Aaz108 { get; set; }
        public string Aaz109 { get; set; }
        public string Aaz110 { get; set; }
        public string Aaz641 { get; set; }
        public string Aaz111 { get; set; }
        public string Aaz112 { get; set; }
        public string Aaz113 { get; set; }
        public string Aaz114 { get; set; }
        public string Aaz119 { get; set; }
        public string Aaz115 { get; set; }
        public string Aaz120 { get; set; }
        public string Aaz121 { get; set; }
        public string Aaz122 { get; set; }
        public string Aaz123 { get; set; }
        public string Aaz124 { get; set; }
        public string Aaz1211 { get; set; }
        public string Aaz1221 { get; set; }
        public string Aaz1231 { get; set; }
        public string Aaz1241 { get; set; }
        public short? Aaz125 { get; set; }
        public string Aaz126 { get; set; }
        public string Aaz127 { get; set; }
        public string Aazud01 { get; set; }
        public string Aazud02 { get; set; }
        public string Aazud03 { get; set; }
        public string Aazud04 { get; set; }
        public string Aazud05 { get; set; }
        public string Aazud06 { get; set; }
        public decimal? Aazud07 { get; set; }
        public decimal? Aazud08 { get; set; }
        public decimal? Aazud09 { get; set; }
        public int? Aazud10 { get; set; }
        public int? Aazud11 { get; set; }
        public int? Aazud12 { get; set; }
        public DateTime? Aazud13 { get; set; }
        public DateTime? Aazud14 { get; set; }
        public DateTime? Aazud15 { get; set; }
        public string Aaz116 { get; set; }
        public string Aaz130 { get; set; }
    }
}
