using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class AlaFile
    {
        public string Ala01 { get; set; }
        public string Ala02 { get; set; }
        public string Ala03 { get; set; }
        public string Ala04 { get; set; }
        public string Ala05 { get; set; }
        public string Ala06 { get; set; }
        public string Ala07 { get; set; }
        public DateTime? Ala08 { get; set; }
        public string Ala09 { get; set; }
        public string Ala10 { get; set; }
        public DateTime? Ala11 { get; set; }
        public string Ala12 { get; set; }
        public short? Ala13 { get; set; }
        public string Ala14 { get; set; }
        public string Ala20 { get; set; }
        public decimal? Ala21 { get; set; }
        public short? Ala22 { get; set; }
        public decimal? Ala23 { get; set; }
        public decimal? Ala24 { get; set; }
        public decimal? Ala25 { get; set; }
        public decimal? Ala26 { get; set; }
        public string Ala31 { get; set; }
        public string Ala32 { get; set; }
        public string Ala33 { get; set; }
        public decimal? Ala34 { get; set; }
        public string Ala35 { get; set; }
        public string Ala36 { get; set; }
        public string Ala37 { get; set; }
        public string Ala38 { get; set; }
        public string Ala39 { get; set; }
        public string Ala40 { get; set; }
        public string Ala41 { get; set; }
        public string Ala42 { get; set; }
        public string Ala43 { get; set; }
        public string Ala44 { get; set; }
        public decimal? Ala51 { get; set; }
        public decimal? Ala52 { get; set; }
        public decimal? Ala53 { get; set; }
        public decimal? Ala54 { get; set; }
        public decimal? Ala55 { get; set; }
        public decimal? Ala56 { get; set; }
        public decimal? Ala57 { get; set; }
        public decimal? Ala59 { get; set; }
        public decimal? Ala60 { get; set; }
        public decimal? Ala61 { get; set; }
        public string Ala71 { get; set; }
        public string Ala72 { get; set; }
        public string Ala73 { get; set; }
        public string Ala74 { get; set; }
        public string Ala75 { get; set; }
        public short? Ala76 { get; set; }
        public DateTime? Ala77 { get; set; }
        public DateTime? Ala771 { get; set; }
        public string Ala772 { get; set; }
        public decimal? Ala773 { get; set; }
        public decimal? Ala774 { get; set; }
        public decimal? Ala775 { get; set; }
        public string Ala776 { get; set; }
        public decimal? Ala777 { get; set; }
        public string Ala778 { get; set; }
        public string Ala78 { get; set; }
        public decimal? Ala79 { get; set; }
        public string Ala80 { get; set; }
        public string Ala81 { get; set; }
        public string Ala82 { get; set; }
        public int? Ala83 { get; set; }
        public decimal? Ala84 { get; set; }
        public decimal? Ala85 { get; set; }
        public string Ala91 { get; set; }
        public string Ala92 { get; set; }
        public int? Ala93 { get; set; }
        public string Ala931 { get; set; }
        public string Ala932 { get; set; }
        public decimal? Ala94 { get; set; }
        public decimal? Ala951 { get; set; }
        public decimal? Ala952 { get; set; }
        public decimal? Ala953 { get; set; }
        public decimal? Ala95 { get; set; }
        public string Ala96 { get; set; }
        public string Alaclos { get; set; }
        public string Alafirm { get; set; }
        public DateTime? Alainpd { get; set; }
        public string Alamksg { get; set; }
        public string Alasign { get; set; }
        public short? Aladays { get; set; }
        public short? Alaprit { get; set; }
        public short? Alasmax { get; set; }
        public short? Alasseq { get; set; }
        public string Alaacti { get; set; }
        public string Alauser { get; set; }
        public string Alagrup { get; set; }
        public string Alamodu { get; set; }
        public DateTime? Aladate { get; set; }
        public DateTime? Ala86 { get; set; }
        public string Ala930 { get; set; }
        public string Ala411 { get; set; }
        public string Ala421 { get; set; }
        public string Ala431 { get; set; }
        public string Ala441 { get; set; }
        public string Ala779 { get; set; }
        public string Ala780 { get; set; }
        public string Alaud01 { get; set; }
        public string Alaud02 { get; set; }
        public string Alaud03 { get; set; }
        public string Alaud04 { get; set; }
        public string Alaud05 { get; set; }
        public string Alaud06 { get; set; }
        public decimal? Alaud07 { get; set; }
        public decimal? Alaud08 { get; set; }
        public decimal? Alaud09 { get; set; }
        public int? Alaud10 { get; set; }
        public int? Alaud11 { get; set; }
        public int? Alaud12 { get; set; }
        public DateTime? Alaud13 { get; set; }
        public DateTime? Alaud14 { get; set; }
        public DateTime? Alaud15 { get; set; }
        public string Alalegal { get; set; }
        public string Ala97 { get; set; }
        public string Alaoriu { get; set; }
        public string Alaorig { get; set; }
    }
}
