using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class ApaFile
    {
        public string Apa00 { get; set; }
        public string Apa01 { get; set; }
        public DateTime? Apa02 { get; set; }
        public string Apa05 { get; set; }
        public string Apa06 { get; set; }
        public string Apa07 { get; set; }
        public string Apa08 { get; set; }
        public DateTime? Apa09 { get; set; }
        public string Apa11 { get; set; }
        public DateTime? Apa12 { get; set; }
        public string Apa13 { get; set; }
        public decimal? Apa14 { get; set; }
        public string Apa15 { get; set; }
        public decimal? Apa16 { get; set; }
        public string Apa17 { get; set; }
        public string Apa171 { get; set; }
        public string Apa172 { get; set; }
        public short? Apa173 { get; set; }
        public short? Apa174 { get; set; }
        public int? Apa175 { get; set; }
        public string Apa18 { get; set; }
        public string Apa19 { get; set; }
        public decimal? Apa20 { get; set; }
        public string Apa21 { get; set; }
        public string Apa22 { get; set; }
        public string Apa23 { get; set; }
        public short? Apa24 { get; set; }
        public string Apa25 { get; set; }
        public decimal Apa31f { get; set; }
        public decimal Apa32f { get; set; }
        public decimal Apa33f { get; set; }
        public decimal Apa34f { get; set; }
        public decimal Apa35f { get; set; }
        public decimal Apa31 { get; set; }
        public decimal Apa32 { get; set; }
        public decimal Apa33 { get; set; }
        public decimal Apa34 { get; set; }
        public decimal Apa35 { get; set; }
        public string Apa36 { get; set; }
        public string Apa41 { get; set; }
        public string Apa42 { get; set; }
        public DateTime? Apa43 { get; set; }
        public string Apa44 { get; set; }
        public DateTime? Apa45 { get; set; }
        public string Apa46 { get; set; }
        public string Apa51 { get; set; }
        public string Apa52 { get; set; }
        public string Apa53 { get; set; }
        public string Apa54 { get; set; }
        public string Apa55 { get; set; }
        public string Apa56 { get; set; }
        public decimal Apa57f { get; set; }
        public decimal? Apa57 { get; set; }
        public string Apa58 { get; set; }
        public string Apa59 { get; set; }
        public decimal Apa60f { get; set; }
        public decimal Apa61f { get; set; }
        public decimal Apa60 { get; set; }
        public decimal Apa61 { get; set; }
        public string Apa62 { get; set; }
        public string Apa63 { get; set; }
        public DateTime? Apa64 { get; set; }
        public decimal Apa65f { get; set; }
        public decimal Apa65 { get; set; }
        public string Apa66 { get; set; }
        public string Apa67 { get; set; }
        public string Apa68 { get; set; }
        public string Apa69 { get; set; }
        public string Apa70 { get; set; }
        public string Apa71 { get; set; }
        public decimal? Apa72 { get; set; }
        public decimal? Apa73 { get; set; }
        public string Apa74 { get; set; }
        public string Apa75 { get; set; }
        public string Apa99 { get; set; }
        public DateTime? Apainpd { get; set; }
        public string Apamksg { get; set; }
        public string Apasign { get; set; }
        public short? Apadays { get; set; }
        public short? Apaprit { get; set; }
        public short? Apasmax { get; set; }
        public short? Apasseq { get; set; }
        public short? Apaprno { get; set; }
        public string Apaacti { get; set; }
        public string Apauser { get; set; }
        public string Apagrup { get; set; }
        public string Apamodu { get; set; }
        public DateTime? Apadate { get; set; }
        public string Apa100 { get; set; }
        public string Apa930 { get; set; }
        public string Apa511 { get; set; }
        public string Apa521 { get; set; }
        public string Apa531 { get; set; }
        public string Apa541 { get; set; }
        public string Apa992 { get; set; }
        public decimal? Apa37 { get; set; }
        public decimal? Apa37f { get; set; }
        public string Apa101 { get; set; }
        public string Apa102 { get; set; }
        public string Apa26 { get; set; }
        public string Apaud01 { get; set; }
        public string Apaud02 { get; set; }
        public string Apaud03 { get; set; }
        public string Apaud04 { get; set; }
        public string Apaud05 { get; set; }
        public string Apaud06 { get; set; }
        public decimal? Apaud07 { get; set; }
        public decimal? Apaud08 { get; set; }
        public decimal? Apaud09 { get; set; }
        public int? Apaud10 { get; set; }
        public int? Apaud11 { get; set; }
        public int? Apaud12 { get; set; }
        public DateTime? Apaud13 { get; set; }
        public DateTime? Apaud14 { get; set; }
        public DateTime? Apaud15 { get; set; }
        public string Apa76 { get; set; }
        public string Apalegal { get; set; }
        public string Apa77 { get; set; }
        public string Apaoriu { get; set; }
        public string Apaorig { get; set; }
        public string Apa78 { get; set; }
        public string Apa79 { get; set; }
    }
}
