using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class AzaFile
    {
        public string Aza01 { get; set; }
        public string Aza02 { get; set; }
        public string Aza03 { get; set; }
        public string Aza04 { get; set; }
        public string Aza05 { get; set; }
        public string Aza06 { get; set; }
        public string Aza07 { get; set; }
        public string Aza08 { get; set; }
        public string Aza09 { get; set; }
        public string Aza10 { get; set; }
        public string Aza11 { get; set; }
        public string Aza12 { get; set; }
        public string Aza13 { get; set; }
        public string Aza14 { get; set; }
        public string Aza15 { get; set; }
        public string Aza16 { get; set; }
        public string Aza17 { get; set; }
        public string Aza18 { get; set; }
        public string Aza19 { get; set; }
        public string Aza20 { get; set; }
        public string Aza21 { get; set; }
        public string Aza22 { get; set; }
        public string Aza23 { get; set; }
        public string Aza24 { get; set; }
        public string Aza25 { get; set; }
        public string Aza26 { get; set; }
        public string Aza27 { get; set; }
        public string Aza28 { get; set; }
        public string Aza29 { get; set; }
        public string Aza30 { get; set; }
        public string Aza31 { get; set; }
        public string Aza32 { get; set; }
        public int? Aza33 { get; set; }
        public int? Aza34 { get; set; }
        public string Aza35 { get; set; }
        public string Aza36 { get; set; }
        public int? Aza37 { get; set; }
        public short? Aza38 { get; set; }
        public string Aza39 { get; set; }
        public string Aza40 { get; set; }
        public string Azauser { get; set; }
        public string Azagrup { get; set; }
        public string Azamodu { get; set; }
        public DateTime? Azadate { get; set; }
        public string Aza41 { get; set; }
        public string Aza42 { get; set; }
        public string Aza43 { get; set; }
        public string Aza44 { get; set; }
        public string Aza45 { get; set; }
        public string Aza46 { get; set; }
        public string Aza47 { get; set; }
        public string Aza48 { get; set; }
        public string Aza49 { get; set; }
        public string Aza50 { get; set; }
        public string Aza51 { get; set; }
        public string Aza52 { get; set; }
        public string Aza53 { get; set; }
        public short? Aza54 { get; set; }
        public int? Aza55 { get; set; }
        public string Aza56 { get; set; }
        public string Aza57 { get; set; }
        public string Aza58 { get; set; }
        public string Aza59 { get; set; }
        public string Aza60 { get; set; }
        public string Aza61 { get; set; }
        public string Aza62 { get; set; }
        public string Aza63 { get; set; }
        public string Aza64 { get; set; }
        public string Aza65 { get; set; }
        public string Aza66 { get; set; }
        public string Aza67 { get; set; }
        public string Aza68 { get; set; }
        public string Aza69 { get; set; }
        public string Aza70 { get; set; }
        public string Aza71 { get; set; }
        public string Aza72 { get; set; }
        public string Aza81 { get; set; }
        public string Aza82 { get; set; }
        public string Aza75 { get; set; }
        public string Aza76 { get; set; }
        public string Aza73 { get; set; }
        public string Aza74 { get; set; }
        public string Aza77 { get; set; }
        public short Aza83 { get; set; }
        public short? Aza84 { get; set; }
        public string Aza85 { get; set; }
        public string Aza86 { get; set; }
        public string Aza78 { get; set; }
        public string Aza90 { get; set; }
        public string Aza91 { get; set; }
        public string Aza92 { get; set; }
        public string Aza93 { get; set; }
        public string Aza88 { get; set; }
        public string Aza89 { get; set; }
        public string Aza94 { get; set; }
        public string Azaorig { get; set; }
        public string Azaoriu { get; set; }
        public string Aza95 { get; set; }
        public string Aza96 { get; set; }
        public short? Aza100 { get; set; }
        public string Aza101 { get; set; }
        public string Aza102 { get; set; }
        public string Aza103 { get; set; }
        public string Aza104 { get; set; }
        public string Aza97 { get; set; }
        public short? Aza98 { get; set; }
        public string Aza99 { get; set; }
        public string Aza107 { get; set; }
        public string Aza108 { get; set; }
        public string Aza123 { get; set; }
        public string Aza109 { get; set; }
        public string Aza121 { get; set; }
        public string Aza122 { get; set; }
        public string Azaud01 { get; set; }
        public string Azaud02 { get; set; }
        public string Azaud03 { get; set; }
        public string Azaud04 { get; set; }
        public string Azaud05 { get; set; }
        public string Azaud06 { get; set; }
        public decimal? Azaud07 { get; set; }
        public decimal? Azaud08 { get; set; }
        public decimal? Azaud09 { get; set; }
        public int? Azaud10 { get; set; }
        public int? Azaud11 { get; set; }
        public int? Azaud12 { get; set; }
        public DateTime? Azaud13 { get; set; }
        public DateTime? Azaud14 { get; set; }
        public DateTime? Azaud15 { get; set; }
    }
}
