using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class CccFile
    {
        public string Ccc01 { get; set; }
        public short Ccc02 { get; set; }
        public short Ccc03 { get; set; }
        public short? Ccc04 { get; set; }
        public short? Ccc05 { get; set; }
        public short? Ccc06 { get; set; }
        public decimal Ccc11 { get; set; }
        public decimal Ccc12 { get; set; }
        public decimal Ccc12a { get; set; }
        public decimal Ccc12b { get; set; }
        public decimal Ccc12c { get; set; }
        public decimal Ccc12d { get; set; }
        public decimal Ccc12e { get; set; }
        public decimal Ccc21 { get; set; }
        public decimal Ccc22 { get; set; }
        public decimal Ccc22a { get; set; }
        public decimal Ccc22b { get; set; }
        public decimal Ccc22c { get; set; }
        public decimal Ccc22d { get; set; }
        public decimal Ccc22e { get; set; }
        public decimal Ccc23 { get; set; }
        public decimal Ccc23a { get; set; }
        public decimal Ccc23b { get; set; }
        public decimal Ccc23c { get; set; }
        public decimal Ccc23d { get; set; }
        public decimal Ccc23e { get; set; }
        public decimal Ccc25 { get; set; }
        public decimal Ccc26 { get; set; }
        public decimal Ccc26a { get; set; }
        public decimal Ccc26b { get; set; }
        public decimal Ccc26c { get; set; }
        public decimal Ccc26d { get; set; }
        public decimal Ccc26e { get; set; }
        public decimal Ccc27 { get; set; }
        public decimal Ccc28 { get; set; }
        public decimal Ccc28a { get; set; }
        public decimal Ccc28b { get; set; }
        public decimal Ccc28c { get; set; }
        public decimal Ccc28d { get; set; }
        public decimal Ccc28e { get; set; }
        public decimal Ccc31 { get; set; }
        public decimal Ccc32 { get; set; }
        public decimal Ccc41 { get; set; }
        public decimal Ccc42 { get; set; }
        public decimal? Ccc43 { get; set; }
        public decimal? Ccc44 { get; set; }
        public decimal Ccc51 { get; set; }
        public decimal Ccc52 { get; set; }
        public decimal Ccc61 { get; set; }
        public decimal Ccc62 { get; set; }
        public decimal? Ccc62a { get; set; }
        public decimal? Ccc62b { get; set; }
        public decimal? Ccc62c { get; set; }
        public decimal? Ccc62d { get; set; }
        public decimal? Ccc62e { get; set; }
        public decimal Ccc63 { get; set; }
        public decimal? Ccc64 { get; set; }
        public decimal? Ccc65 { get; set; }
        public decimal? Ccc66 { get; set; }
        public decimal? Ccc66a { get; set; }
        public decimal? Ccc66b { get; set; }
        public decimal? Ccc66c { get; set; }
        public decimal? Ccc66d { get; set; }
        public decimal? Ccc66e { get; set; }
        public decimal Ccc71 { get; set; }
        public decimal Ccc72 { get; set; }
        public decimal Ccc91 { get; set; }
        public decimal Ccc92 { get; set; }
        public decimal Ccc92a { get; set; }
        public decimal Ccc92b { get; set; }
        public decimal Ccc92c { get; set; }
        public decimal Ccc92d { get; set; }
        public decimal Ccc92e { get; set; }
        public decimal Ccc93 { get; set; }
        public decimal? Ccc93a { get; set; }
        public decimal? Ccc93b { get; set; }
        public decimal? Ccc93c { get; set; }
        public decimal? Ccc93d { get; set; }
        public decimal? Ccc93e { get; set; }
        public string Cccuser { get; set; }
        public DateTime? Cccdate { get; set; }
        public string Ccctime { get; set; }
        public decimal? Ccc211 { get; set; }
        public decimal? Ccc212 { get; set; }
        public decimal? Ccc213 { get; set; }
        public decimal? Ccc214 { get; set; }
        public decimal? Ccc215 { get; set; }
        public decimal? Ccc221 { get; set; }
        public decimal? Ccc222 { get; set; }
        public decimal? Ccc223 { get; set; }
        public decimal? Ccc224 { get; set; }
        public decimal? Ccc225 { get; set; }
        public decimal? Ccc22a1 { get; set; }
        public decimal? Ccc22a2 { get; set; }
        public decimal? Ccc22a3 { get; set; }
        public decimal? Ccc22a4 { get; set; }
        public decimal? Ccc22a5 { get; set; }
        public decimal? Ccc22b1 { get; set; }
        public decimal? Ccc22b2 { get; set; }
        public decimal? Ccc22b3 { get; set; }
        public decimal? Ccc22b4 { get; set; }
        public decimal? Ccc22b5 { get; set; }
        public decimal? Ccc22c1 { get; set; }
        public decimal? Ccc22c2 { get; set; }
        public decimal? Ccc22c3 { get; set; }
        public decimal? Ccc22c4 { get; set; }
        public decimal? Ccc22c5 { get; set; }
        public decimal? Ccc22d1 { get; set; }
        public decimal? Ccc22d2 { get; set; }
        public decimal? Ccc22d3 { get; set; }
        public decimal? Ccc22d4 { get; set; }
        public decimal? Ccc22d5 { get; set; }
        public decimal? Ccc22e1 { get; set; }
        public decimal? Ccc22e2 { get; set; }
        public decimal? Ccc22e3 { get; set; }
        public decimal? Ccc22e4 { get; set; }
        public decimal? Ccc22e5 { get; set; }
        public decimal? Ccc81 { get; set; }
        public decimal? Ccc82 { get; set; }
        public decimal? Ccc82a { get; set; }
        public decimal? Ccc82b { get; set; }
        public decimal? Ccc82c { get; set; }
        public decimal? Ccc82d { get; set; }
        public decimal? Ccc82e { get; set; }
        public string Ccc07 { get; set; }
        public string Ccc08 { get; set; }
        public decimal? Ccc12f { get; set; }
        public decimal? Ccc12g { get; set; }
        public decimal? Ccc12h { get; set; }
        public decimal? Ccc22f { get; set; }
        public decimal? Ccc22f1 { get; set; }
        public decimal? Ccc22f2 { get; set; }
        public decimal? Ccc22f3 { get; set; }
        public decimal? Ccc22f4 { get; set; }
        public decimal? Ccc22f5 { get; set; }
        public decimal? Ccc22g { get; set; }
        public decimal? Ccc22g1 { get; set; }
        public decimal? Ccc22g2 { get; set; }
        public decimal? Ccc22g3 { get; set; }
        public decimal? Ccc22g4 { get; set; }
        public decimal? Ccc22g5 { get; set; }
        public decimal? Ccc22h { get; set; }
        public decimal? Ccc22h1 { get; set; }
        public decimal? Ccc22h2 { get; set; }
        public decimal? Ccc22h3 { get; set; }
        public decimal? Ccc22h4 { get; set; }
        public decimal? Ccc22h5 { get; set; }
        public decimal? Ccc23f { get; set; }
        public decimal? Ccc23g { get; set; }
        public decimal? Ccc23h { get; set; }
        public decimal? Ccc26f { get; set; }
        public decimal? Ccc26g { get; set; }
        public decimal? Ccc26h { get; set; }
        public decimal? Ccc28f { get; set; }
        public decimal? Ccc28g { get; set; }
        public decimal? Ccc28h { get; set; }
        public decimal? Ccc62f { get; set; }
        public decimal? Ccc62g { get; set; }
        public decimal? Ccc62h { get; set; }
        public decimal? Ccc66f { get; set; }
        public decimal? Ccc66g { get; set; }
        public decimal? Ccc66h { get; set; }
        public decimal? Ccc82f { get; set; }
        public decimal? Ccc82g { get; set; }
        public decimal? Ccc82h { get; set; }
        public decimal? Ccc92f { get; set; }
        public decimal? Ccc92g { get; set; }
        public decimal? Ccc92h { get; set; }
        public decimal? Ccc93f { get; set; }
        public decimal? Ccc93g { get; set; }
        public decimal? Ccc93h { get; set; }
        public string Cccud01 { get; set; }
        public string Cccud02 { get; set; }
        public string Cccud03 { get; set; }
        public string Cccud04 { get; set; }
        public string Cccud05 { get; set; }
        public string Cccud06 { get; set; }
        public decimal? Cccud07 { get; set; }
        public decimal? Cccud08 { get; set; }
        public decimal? Cccud09 { get; set; }
        public int? Cccud10 { get; set; }
        public int? Cccud11 { get; set; }
        public int? Cccud12 { get; set; }
        public DateTime? Cccud13 { get; set; }
        public DateTime? Cccud14 { get; set; }
        public DateTime? Cccud15 { get; set; }
        public string Cccorig { get; set; }
        public string Cccoriu { get; set; }
        public decimal? Ccc216 { get; set; }
        public decimal? Ccc226 { get; set; }
        public decimal? Ccc22a6 { get; set; }
        public decimal? Ccc22b6 { get; set; }
        public decimal? Ccc22c6 { get; set; }
        public decimal? Ccc22d6 { get; set; }
        public decimal? Ccc22e6 { get; set; }
        public decimal? Ccc22f6 { get; set; }
        public decimal? Ccc22g6 { get; set; }
        public decimal? Ccc22h6 { get; set; }
        public string Ccclegal { get; set; }
    }
}
