using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class CchFile
    {
        public string Cch01 { get; set; }
        public short Cch02 { get; set; }
        public short Cch03 { get; set; }
        public string Cch04 { get; set; }
        public string Cch05 { get; set; }
        public decimal Cch11 { get; set; }
        public decimal Cch12 { get; set; }
        public decimal Cch12a { get; set; }
        public decimal Cch12b { get; set; }
        public decimal Cch12c { get; set; }
        public decimal Cch12d { get; set; }
        public decimal Cch12e { get; set; }
        public decimal Cch21 { get; set; }
        public decimal Cch22 { get; set; }
        public decimal Cch22a { get; set; }
        public decimal Cch22b { get; set; }
        public decimal Cch22c { get; set; }
        public decimal Cch22d { get; set; }
        public decimal Cch22e { get; set; }
        public decimal Cch31 { get; set; }
        public decimal Cch32 { get; set; }
        public decimal Cch32a { get; set; }
        public decimal Cch32b { get; set; }
        public decimal Cch32c { get; set; }
        public decimal Cch32d { get; set; }
        public decimal Cch32e { get; set; }
        public decimal Cch41 { get; set; }
        public decimal Cch42 { get; set; }
        public decimal Cch42a { get; set; }
        public decimal Cch42b { get; set; }
        public decimal Cch42c { get; set; }
        public decimal Cch42d { get; set; }
        public decimal Cch42e { get; set; }
        public decimal? Cch51 { get; set; }
        public decimal? Cch52 { get; set; }
        public decimal? Cch52a { get; set; }
        public decimal? Cch52b { get; set; }
        public decimal? Cch52c { get; set; }
        public decimal? Cch52d { get; set; }
        public decimal? Cch52e { get; set; }
        public decimal? Cch53 { get; set; }
        public decimal? Cch54 { get; set; }
        public decimal? Cch54a { get; set; }
        public decimal? Cch54b { get; set; }
        public decimal? Cch54c { get; set; }
        public decimal? Cch54d { get; set; }
        public decimal? Cch54e { get; set; }
        public decimal? Cch55 { get; set; }
        public decimal? Cch56 { get; set; }
        public decimal? Cch56a { get; set; }
        public decimal? Cch56b { get; set; }
        public decimal? Cch56c { get; set; }
        public decimal? Cch56d { get; set; }
        public decimal? Cch56e { get; set; }
        public decimal? Cch57 { get; set; }
        public decimal? Cch58 { get; set; }
        public decimal? Cch58a { get; set; }
        public decimal? Cch58b { get; set; }
        public decimal? Cch58c { get; set; }
        public decimal? Cch58d { get; set; }
        public decimal? Cch58e { get; set; }
        public decimal? Cch59 { get; set; }
        public decimal? Cch60 { get; set; }
        public decimal? Cch60a { get; set; }
        public decimal? Cch60b { get; set; }
        public decimal? Cch60c { get; set; }
        public decimal? Cch60d { get; set; }
        public decimal? Cch60e { get; set; }
        public decimal Cch91 { get; set; }
        public decimal Cch92 { get; set; }
        public decimal Cch92a { get; set; }
        public decimal Cch92b { get; set; }
        public decimal Cch92c { get; set; }
        public decimal Cch92d { get; set; }
        public decimal Cch92e { get; set; }
        public string Cchuser { get; set; }
        public DateTime? Cchdate { get; set; }
        public string Cchtime { get; set; }
        public decimal? Cch311 { get; set; }
        public string Cch06 { get; set; }
        public string Cch07 { get; set; }
        public decimal? Cch12f { get; set; }
        public decimal? Cch12g { get; set; }
        public decimal? Cch12h { get; set; }
        public decimal? Cch22f { get; set; }
        public decimal? Cch22g { get; set; }
        public decimal? Cch22h { get; set; }
        public decimal? Cch32f { get; set; }
        public decimal? Cch32g { get; set; }
        public decimal? Cch32h { get; set; }
        public decimal? Cch42f { get; set; }
        public decimal? Cch42g { get; set; }
        public decimal? Cch42h { get; set; }
        public decimal? Cch52f { get; set; }
        public decimal? Cch52g { get; set; }
        public decimal? Cch52h { get; set; }
        public decimal? Cch54f { get; set; }
        public decimal? Cch54g { get; set; }
        public decimal? Cch54h { get; set; }
        public decimal? Cch56f { get; set; }
        public decimal? Cch56g { get; set; }
        public decimal? Cch56h { get; set; }
        public decimal? Cch58f { get; set; }
        public decimal? Cch58g { get; set; }
        public decimal? Cch58h { get; set; }
        public decimal? Cch60f { get; set; }
        public decimal? Cch60g { get; set; }
        public decimal? Cch60h { get; set; }
        public decimal? Cch92f { get; set; }
        public decimal? Cch92g { get; set; }
        public decimal? Cch92h { get; set; }
        public string Cchud01 { get; set; }
        public string Cchud02 { get; set; }
        public string Cchud03 { get; set; }
        public string Cchud04 { get; set; }
        public string Cchud05 { get; set; }
        public string Cchud06 { get; set; }
        public decimal? Cchud07 { get; set; }
        public decimal? Cchud08 { get; set; }
        public decimal? Cchud09 { get; set; }
        public int? Cchud10 { get; set; }
        public int? Cchud11 { get; set; }
        public int? Cchud12 { get; set; }
        public DateTime? Cchud13 { get; set; }
        public DateTime? Cchud14 { get; set; }
        public DateTime? Cchud15 { get; set; }
        public string Cchlegal { get; set; }
        public string Cchorig { get; set; }
        public string Cchoriu { get; set; }
    }
}
