using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class CpaFile
    {
        public string Cpa00 { get; set; }
        public string Cpa01 { get; set; }
        public string Cpa02 { get; set; }
        public short? Cpa03 { get; set; }
        public decimal? Cpa04 { get; set; }
        public decimal? Cpa05 { get; set; }
        public int Cpa06 { get; set; }
        public short Cpa061 { get; set; }
        public string Cpa07 { get; set; }
        public string Cpa08 { get; set; }
        public string Cpa09 { get; set; }
        public string Cpa10 { get; set; }
        public decimal? Cpa11 { get; set; }
        public decimal? Cpa12 { get; set; }
        public decimal? Cpa13 { get; set; }
        public decimal? Cpa14 { get; set; }
        public decimal? Cpa15 { get; set; }
        public short? Cpa16 { get; set; }
        public decimal? Cpa17 { get; set; }
        public decimal? Cpa18 { get; set; }
        public short? Cpa19 { get; set; }
        public short? Cpa20 { get; set; }
        public decimal? Cpa21 { get; set; }
        public short? Cpa22 { get; set; }
        public short? Cpa23 { get; set; }
        public short? Cpa24 { get; set; }
        public short? Cpa25 { get; set; }
        public decimal? Cpa26 { get; set; }
        public decimal? Cpa27 { get; set; }
        public decimal? Cpa28 { get; set; }
        public decimal? Cpa29 { get; set; }
        public decimal? Cpa30 { get; set; }
        public string Cpa31 { get; set; }
        public string Cpa311 { get; set; }
        public string Cpa32 { get; set; }
        public decimal? Cpa33 { get; set; }
        public decimal? Cpa34 { get; set; }
        public short? Cpa35 { get; set; }
        public short? Cpa36 { get; set; }
        public decimal? Cpa37 { get; set; }
        public short? Cpa38 { get; set; }
        public short? Cpa39 { get; set; }
        public decimal? Cpa40 { get; set; }
        public short? Cpa41 { get; set; }
        public short? Cpa42 { get; set; }
        public decimal? Cpa43 { get; set; }
        public short? Cpa44 { get; set; }
        public short? Cpa45 { get; set; }
        public decimal? Cpa46 { get; set; }
        public short? Cpa47 { get; set; }
        public short? Cpa48 { get; set; }
        public decimal? Cpa49 { get; set; }
        public short? Cpa50 { get; set; }
        public short? Cpa51 { get; set; }
        public decimal? Cpa52 { get; set; }
        public short? Cpa53 { get; set; }
        public short? Cpa54 { get; set; }
        public decimal? Cpa55 { get; set; }
        public short? Cpa56 { get; set; }
        public short? Cpa57 { get; set; }
        public decimal? Cpa58 { get; set; }
        public decimal? Cpa59 { get; set; }
        public decimal? Cpa60 { get; set; }
        public decimal? Cpa61 { get; set; }
        public decimal? Cpa62 { get; set; }
        public decimal? Cpa63 { get; set; }
        public decimal? Cpa64 { get; set; }
        public decimal? Cpa65 { get; set; }
        public decimal? Cpa66 { get; set; }
        public decimal? Cpa67 { get; set; }
        public decimal? Cpa68 { get; set; }
        public decimal? Cpa69 { get; set; }
        public decimal? Cpa70 { get; set; }
        public string Cpa71 { get; set; }
        public string Cpa72 { get; set; }
        public decimal? Cpa73 { get; set; }
        public decimal? Cpa74 { get; set; }
        public short? Cpa75 { get; set; }
        public decimal? Cpa76 { get; set; }
        public decimal? Cpa77 { get; set; }
        public string Cpa78 { get; set; }
        public decimal? Cpa79 { get; set; }
        public decimal? Cpa80 { get; set; }
        public string Cpa81 { get; set; }
        public string Cpa82 { get; set; }
        public string Cpa83 { get; set; }
        public string Cpa84 { get; set; }
        public string Cpa85 { get; set; }
        public string Cpa86 { get; set; }
        public string Cpa87 { get; set; }
        public string Cpa88 { get; set; }
        public string Cpa89 { get; set; }
        public string Cpa90 { get; set; }
        public string Cpa91 { get; set; }
        public string Cpa92 { get; set; }
        public string Cpa93 { get; set; }
        public string Cpa94 { get; set; }
        public string Cpa95 { get; set; }
        public string Cpa96 { get; set; }
        public string Cpa97 { get; set; }
        public string Cpa98 { get; set; }
        public string Cpa99 { get; set; }
        public decimal? Cpa100 { get; set; }
        public decimal? Cpa101 { get; set; }
        public decimal? Cpa102 { get; set; }
        public decimal? Cpa103 { get; set; }
        public decimal? Cpa104 { get; set; }
        public decimal? Cpa105 { get; set; }
        public decimal? Cpa106 { get; set; }
        public decimal? Cpa107 { get; set; }
        public string Cpa108 { get; set; }
        public string Cpa109 { get; set; }
        public decimal? Cpa110 { get; set; }
        public string Cpa111 { get; set; }
        public string Cpa112 { get; set; }
        public decimal? Cpa113 { get; set; }
        public string Cpa114 { get; set; }
        public string Cpa115 { get; set; }
        public decimal? Cpa116 { get; set; }
        public decimal? Cpa117 { get; set; }
        public string Cpa118 { get; set; }
        public string Cpa130 { get; set; }
        public string Cpa131 { get; set; }
        public string Cpa132 { get; set; }
        public string Cpa133 { get; set; }
        public string Cpa134 { get; set; }
        public string Cpauser { get; set; }
        public string Cpagrup { get; set; }
        public string Cpamodu { get; set; }
        public DateTime? Cpadate { get; set; }
        public decimal? Cpa140 { get; set; }
        public decimal? Cpa141 { get; set; }
        public string Cpa135 { get; set; }
        public string Cpa120 { get; set; }
        public string Cpa121 { get; set; }
        public string Cpa122 { get; set; }
        public string Cpa123 { get; set; }
        public string Cpa124 { get; set; }
        public string Cpa125 { get; set; }
        public string Cpa126 { get; set; }
        public string Cpa127 { get; set; }
        public string Cpa128 { get; set; }
        public string Cpa129 { get; set; }
        public string Cpa143 { get; set; }
        public string Cpa144 { get; set; }
        public string Cpa145 { get; set; }
        public string Cpa142 { get; set; }
        public decimal? Cpa146 { get; set; }
        public decimal? Cpa147 { get; set; }
        public string Cpa148 { get; set; }
        public string Cpa149 { get; set; }
        public string Cpa150 { get; set; }
        public string Cpa151 { get; set; }
        public string Cpa152 { get; set; }
        public string Cpa831 { get; set; }
        public string Cpa841 { get; set; }
        public string Cpa851 { get; set; }
        public string Cpa861 { get; set; }
        public string Cpa871 { get; set; }
        public string Cpa881 { get; set; }
        public string Cpa891 { get; set; }
        public string Cpa901 { get; set; }
        public string Cpa911 { get; set; }
        public string Cpa921 { get; set; }
        public string Cpa931 { get; set; }
        public string Cpa941 { get; set; }
        public string Cpa951 { get; set; }
        public string Cpa961 { get; set; }
        public string Cpa971 { get; set; }
        public string Cpa981 { get; set; }
        public string Cpa991 { get; set; }
        public string Cpa153 { get; set; }
        public string Cpa154 { get; set; }
        public string Cpa155 { get; set; }
        public string Cpa156 { get; set; }
        public string Cpa157 { get; set; }
        public string Cpa158 { get; set; }
        public string Cpa159 { get; set; }
        public decimal? Cpa171 { get; set; }
        public decimal? Cpa172 { get; set; }
        public decimal? Cpa173 { get; set; }
        public decimal? Cpa174 { get; set; }
        public string Cpaorig { get; set; }
        public string Cpaoriu { get; set; }
    }
}
