using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class CpfFile
    {
        public string Cpf01 { get; set; }
        public string Cpf02 { get; set; }
        public string Cpf03 { get; set; }
        public DateTime? Cpf04 { get; set; }
        public string Cpf05 { get; set; }
        public string Cpf06 { get; set; }
        public string Cpf07 { get; set; }
        public string Cpf08 { get; set; }
        public string Cpf09 { get; set; }
        public string Cpf10 { get; set; }
        public string Cpf11 { get; set; }
        public string Cpf12 { get; set; }
        public string Cpf13 { get; set; }
        public string Cpf14 { get; set; }
        public string Cpf15 { get; set; }
        public string Cpf16 { get; set; }
        public string Cpf17 { get; set; }
        public string Cpf18 { get; set; }
        public string Cpf19 { get; set; }
        public short? Cpf20 { get; set; }
        public string Cpf21 { get; set; }
        public string Cpf22 { get; set; }
        public string Cpf23 { get; set; }
        public string Cpf24 { get; set; }
        public DateTime? Cpf25 { get; set; }
        public string Cpf26 { get; set; }
        public string Cpf27 { get; set; }
        public string Cpf28 { get; set; }
        public string Cpf281 { get; set; }
        public string Cpf29 { get; set; }
        public string Cpf30 { get; set; }
        public string Cpf31 { get; set; }
        public DateTime? Cpf32 { get; set; }
        public DateTime? Cpf33 { get; set; }
        public string Cpf34 { get; set; }
        public short? Cpf341 { get; set; }
        public DateTime? Cpf35 { get; set; }
        public string Cpf36 { get; set; }
        public string Cpf37 { get; set; }
        public decimal? Cpf38 { get; set; }
        public DateTime? Cpf39 { get; set; }
        public string Cpf40 { get; set; }
        public string Cpf41 { get; set; }
        public string Cpf42 { get; set; }
        public string Cpf43 { get; set; }
        public string Cpf432 { get; set; }
        public string Cpf44 { get; set; }
        public string Cpf441 { get; set; }
        public string Cpf442 { get; set; }
        public string Cpf45 { get; set; }
        public string Cpf46 { get; set; }
        public decimal? Cpf47 { get; set; }
        public string Cpf48 { get; set; }
        public decimal? Cpf49 { get; set; }
        public string Cpf50 { get; set; }
        public decimal? Cpf51 { get; set; }
        public decimal? Cpf52 { get; set; }
        public decimal? Cpf53 { get; set; }
        public string Cpf54 { get; set; }
        public short? Cpf55 { get; set; }
        public DateTime? Cpf56 { get; set; }
        public DateTime? Cpf57 { get; set; }
        public short? Cpf58 { get; set; }
        public DateTime? Cpf59 { get; set; }
        public DateTime? Cpf60 { get; set; }
        public string Cpf61 { get; set; }
        public DateTime? Cpf62 { get; set; }
        public DateTime? Cpf63 { get; set; }
        public string Cpf64 { get; set; }
        public decimal? Cpf65 { get; set; }
        public decimal? Cpf66 { get; set; }
        public DateTime? Cpf67 { get; set; }
        public string Cpf68 { get; set; }
        public decimal? Cpf69 { get; set; }
        public DateTime? Cpf70 { get; set; }
        public decimal? Cpf71 { get; set; }
        public string Cpf72 { get; set; }
        public string Cpf73 { get; set; }
        public string Cpf731 { get; set; }
        public string Cpf74 { get; set; }
        public string Cpf75 { get; set; }
        public string Cpf76 { get; set; }
        public string Cpf77 { get; set; }
        public string Cpf78 { get; set; }
        public DateTime? Cpf791 { get; set; }
        public DateTime? Cpf792 { get; set; }
        public DateTime? Cpf793 { get; set; }
        public decimal? Cpf80 { get; set; }
        public DateTime? Cpf81 { get; set; }
        public DateTime? Cpf82 { get; set; }
        public string Cpf87 { get; set; }
        public string Cpf90 { get; set; }
        public decimal? Cpf91 { get; set; }
        public decimal? Cpf92 { get; set; }
        public string Cpf93 { get; set; }
        public string Cpf94 { get; set; }
        public DateTime? Cpf95 { get; set; }
        public DateTime? Cpf96 { get; set; }
        public string Cpf97 { get; set; }
        public DateTime? Cpf98 { get; set; }
        public DateTime? Cpf99 { get; set; }
        public string Cpf100 { get; set; }
        public string Cpfacti { get; set; }
        public string Cpfuser { get; set; }
        public string Cpfgrup { get; set; }
        public string Cpfmodu { get; set; }
        public DateTime? Cpfdate { get; set; }
        public string Cpf110 { get; set; }
        public DateTime? Cpf111 { get; set; }
        public decimal? Cpf112 { get; set; }
        public decimal? Cpf113 { get; set; }
        public string Cpf114 { get; set; }
        public short? Cpf115 { get; set; }
        public string Cpf116 { get; set; }
        public DateTime? Cpf117 { get; set; }
        public decimal? Cpf118 { get; set; }
        public decimal? Cpf119 { get; set; }
        public string Cpf120 { get; set; }
        public DateTime? Cpf121 { get; set; }
        public string Cpf361 { get; set; }
        public string Cpf581 { get; set; }
        public string Cpf551 { get; set; }
        public decimal? Cpf101 { get; set; }
        public string Cpf130 { get; set; }
        public string Cpf131 { get; set; }
        public string Cpf132 { get; set; }
        public string Cpf601 { get; set; }
        public string Cpf122 { get; set; }
        public string Cpfud01 { get; set; }
        public string Cpfud02 { get; set; }
        public string Cpfud03 { get; set; }
        public string Cpfud04 { get; set; }
        public string Cpfud05 { get; set; }
        public string Cpfud06 { get; set; }
        public decimal? Cpfud07 { get; set; }
        public decimal? Cpfud08 { get; set; }
        public decimal? Cpfud09 { get; set; }
        public int? Cpfud10 { get; set; }
        public int? Cpfud11 { get; set; }
        public int? Cpfud12 { get; set; }
        public DateTime? Cpfud13 { get; set; }
        public DateTime? Cpfud14 { get; set; }
        public DateTime? Cpfud15 { get; set; }
        public string Cpf552 { get; set; }
        public string Cpf790 { get; set; }
        public DateTime? Cpf794 { get; set; }
        public string Cpforiu { get; set; }
        public string Cpforig { get; set; }
    }
}
