using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class CxhFile
    {
        public string Cxh01 { get; set; }
        public string Cxh011 { get; set; }
        public string Cxh012 { get; set; }
        public short Cxh02 { get; set; }
        public short Cxh03 { get; set; }
        public string Cxh04 { get; set; }
        public string Cxh05 { get; set; }
        public decimal Cxh11 { get; set; }
        public decimal Cxh12 { get; set; }
        public decimal Cxh12a { get; set; }
        public decimal Cxh12b { get; set; }
        public decimal Cxh12c { get; set; }
        public decimal Cxh12d { get; set; }
        public decimal Cxh12e { get; set; }
        public decimal Cxh21 { get; set; }
        public decimal Cxh22 { get; set; }
        public decimal Cxh22a { get; set; }
        public decimal Cxh22b { get; set; }
        public decimal Cxh22c { get; set; }
        public decimal Cxh22d { get; set; }
        public decimal Cxh22e { get; set; }
        public decimal Cxh24 { get; set; }
        public decimal Cxh25 { get; set; }
        public decimal Cxh25a { get; set; }
        public decimal Cxh25b { get; set; }
        public decimal Cxh25c { get; set; }
        public decimal Cxh25d { get; set; }
        public decimal Cxh25e { get; set; }
        public decimal Cxh26 { get; set; }
        public decimal Cxh27 { get; set; }
        public decimal Cxh27a { get; set; }
        public decimal Cxh27b { get; set; }
        public decimal Cxh27c { get; set; }
        public decimal Cxh27d { get; set; }
        public decimal Cxh27e { get; set; }
        public decimal Cxh28 { get; set; }
        public decimal Cxh29 { get; set; }
        public decimal Cxh29a { get; set; }
        public decimal Cxh29b { get; set; }
        public decimal Cxh29c { get; set; }
        public decimal Cxh29d { get; set; }
        public decimal Cxh29e { get; set; }
        public decimal Cxh31 { get; set; }
        public decimal Cxh32 { get; set; }
        public decimal Cxh32a { get; set; }
        public decimal Cxh32b { get; set; }
        public decimal Cxh32c { get; set; }
        public decimal Cxh32d { get; set; }
        public decimal Cxh32e { get; set; }
        public decimal Cxh33 { get; set; }
        public decimal Cxh34 { get; set; }
        public decimal Cxh34a { get; set; }
        public decimal Cxh34b { get; set; }
        public decimal Cxh34c { get; set; }
        public decimal Cxh34d { get; set; }
        public decimal Cxh34e { get; set; }
        public decimal Cxh35 { get; set; }
        public decimal Cxh36 { get; set; }
        public decimal Cxh36a { get; set; }
        public decimal Cxh36b { get; set; }
        public decimal Cxh36c { get; set; }
        public decimal Cxh36d { get; set; }
        public decimal Cxh36e { get; set; }
        public decimal Cxh37 { get; set; }
        public decimal Cxh38 { get; set; }
        public decimal Cxh38a { get; set; }
        public decimal Cxh38b { get; set; }
        public decimal Cxh38c { get; set; }
        public decimal Cxh38d { get; set; }
        public decimal Cxh38e { get; set; }
        public decimal Cxh39 { get; set; }
        public decimal Cxh40 { get; set; }
        public decimal Cxh40a { get; set; }
        public decimal Cxh40b { get; set; }
        public decimal Cxh40c { get; set; }
        public decimal Cxh40d { get; set; }
        public decimal Cxh40e { get; set; }
        public decimal Cxh41 { get; set; }
        public decimal Cxh42 { get; set; }
        public decimal Cxh42a { get; set; }
        public decimal Cxh42b { get; set; }
        public decimal Cxh42c { get; set; }
        public decimal Cxh42d { get; set; }
        public decimal Cxh42e { get; set; }
        public decimal Cxh51 { get; set; }
        public decimal Cxh52 { get; set; }
        public decimal Cxh52a { get; set; }
        public decimal Cxh52b { get; set; }
        public decimal Cxh52c { get; set; }
        public decimal Cxh52d { get; set; }
        public decimal Cxh52e { get; set; }
        public decimal Cxh53 { get; set; }
        public decimal Cxh54 { get; set; }
        public decimal Cxh54a { get; set; }
        public decimal Cxh54b { get; set; }
        public decimal Cxh54c { get; set; }
        public decimal Cxh54d { get; set; }
        public decimal Cxh54e { get; set; }
        public decimal Cxh55 { get; set; }
        public decimal Cxh56 { get; set; }
        public decimal Cxh56a { get; set; }
        public decimal Cxh56b { get; set; }
        public decimal Cxh56c { get; set; }
        public decimal Cxh56d { get; set; }
        public decimal Cxh56e { get; set; }
        public decimal Cxh57 { get; set; }
        public decimal Cxh58 { get; set; }
        public decimal Cxh58a { get; set; }
        public decimal Cxh58b { get; set; }
        public decimal Cxh58c { get; set; }
        public decimal Cxh58d { get; set; }
        public decimal Cxh58e { get; set; }
        public decimal Cxh59 { get; set; }
        public decimal Cxh60 { get; set; }
        public decimal Cxh60a { get; set; }
        public decimal Cxh60b { get; set; }
        public decimal Cxh60c { get; set; }
        public decimal Cxh60d { get; set; }
        public decimal Cxh60e { get; set; }
        public decimal Cxh91 { get; set; }
        public decimal Cxh92 { get; set; }
        public decimal Cxh92a { get; set; }
        public decimal Cxh92b { get; set; }
        public decimal Cxh92c { get; set; }
        public decimal Cxh92d { get; set; }
        public decimal Cxh92e { get; set; }
        public string Cxhuser { get; set; }
        public DateTime? Cxhdate { get; set; }
        public string Cxhtime { get; set; }
        public string Cxh06 { get; set; }
        public string Cxh07 { get; set; }
        public decimal? Cxh12f { get; set; }
        public decimal? Cxh12g { get; set; }
        public decimal? Cxh12h { get; set; }
        public decimal? Cxh22f { get; set; }
        public decimal? Cxh22g { get; set; }
        public decimal? Cxh22h { get; set; }
        public decimal? Cxh25f { get; set; }
        public decimal? Cxh25g { get; set; }
        public decimal? Cxh25h { get; set; }
        public decimal? Cxh27f { get; set; }
        public decimal? Cxh27g { get; set; }
        public decimal? Cxh27h { get; set; }
        public decimal? Cxh29f { get; set; }
        public decimal? Cxh29g { get; set; }
        public decimal? Cxh29h { get; set; }
        public decimal? Cxh32f { get; set; }
        public decimal? Cxh32g { get; set; }
        public decimal? Cxh32h { get; set; }
        public decimal? Cxh34f { get; set; }
        public decimal? Cxh34g { get; set; }
        public decimal? Cxh34h { get; set; }
        public decimal? Cxh36f { get; set; }
        public decimal? Cxh36g { get; set; }
        public decimal? Cxh36h { get; set; }
        public decimal? Cxh38f { get; set; }
        public decimal? Cxh38g { get; set; }
        public decimal? Cxh38h { get; set; }
        public decimal? Cxh40f { get; set; }
        public decimal? Cxh40g { get; set; }
        public decimal? Cxh40h { get; set; }
        public decimal? Cxh42f { get; set; }
        public decimal? Cxh42g { get; set; }
        public decimal? Cxh42h { get; set; }
        public decimal? Cxh52f { get; set; }
        public decimal? Cxh52g { get; set; }
        public decimal? Cxh52h { get; set; }
        public decimal? Cxh54f { get; set; }
        public decimal? Cxh54g { get; set; }
        public decimal? Cxh54h { get; set; }
        public decimal? Cxh56f { get; set; }
        public decimal? Cxh56g { get; set; }
        public decimal? Cxh56h { get; set; }
        public decimal? Cxh58f { get; set; }
        public decimal? Cxh58g { get; set; }
        public decimal? Cxh58h { get; set; }
        public decimal? Cxh60f { get; set; }
        public decimal? Cxh60g { get; set; }
        public decimal? Cxh60h { get; set; }
        public decimal? Cxh92f { get; set; }
        public decimal? Cxh92g { get; set; }
        public decimal? Cxh92h { get; set; }
        public string Cxhlegal { get; set; }
        public string Cxhorig { get; set; }
        public string Cxhoriu { get; set; }
        public string Cxh013 { get; set; }
        public short Cxh014 { get; set; }
    }
}
