using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class FajFile
    {
        public string Faj01 { get; set; }
        public string Faj02 { get; set; }
        public string Faj021 { get; set; }
        public string Faj022 { get; set; }
        public string Faj03 { get; set; }
        public string Faj04 { get; set; }
        public string Faj05 { get; set; }
        public string Faj06 { get; set; }
        public string Faj061 { get; set; }
        public string Faj07 { get; set; }
        public string Faj071 { get; set; }
        public string Faj08 { get; set; }
        public string Faj09 { get; set; }
        public string Faj10 { get; set; }
        public string Faj11 { get; set; }
        public string Faj12 { get; set; }
        public decimal? Faj13 { get; set; }
        public decimal? Faj14 { get; set; }
        public decimal? Faj141 { get; set; }
        public string Faj15 { get; set; }
        public decimal? Faj16 { get; set; }
        public short? Faj17 { get; set; }
        public short? Faj171 { get; set; }
        public string Faj18 { get; set; }
        public string Faj19 { get; set; }
        public string Faj20 { get; set; }
        public string Faj21 { get; set; }
        public string Faj22 { get; set; }
        public string Faj23 { get; set; }
        public string Faj24 { get; set; }
        public DateTime? Faj25 { get; set; }
        public DateTime? Faj26 { get; set; }
        public string Faj27 { get; set; }
        public string Faj28 { get; set; }
        public short? Faj29 { get; set; }
        public short? Faj30 { get; set; }
        public decimal? Faj31 { get; set; }
        public decimal? Faj32 { get; set; }
        public decimal? Faj33 { get; set; }
        public string Faj34 { get; set; }
        public decimal? Faj35 { get; set; }
        public short? Faj36 { get; set; }
        public string Faj37 { get; set; }
        public string Faj38 { get; set; }
        public string Faj39 { get; set; }
        public string Faj40 { get; set; }
        public string Faj41 { get; set; }
        public string Faj42 { get; set; }
        public short? Faj421 { get; set; }
        public short? Faj422 { get; set; }
        public short? Faj423 { get; set; }
        public string Faj43 { get; set; }
        public string Faj44 { get; set; }
        public string Faj45 { get; set; }
        public short? Faj451 { get; set; }
        public string Faj46 { get; set; }
        public short? Faj461 { get; set; }
        public DateTime? Faj462 { get; set; }
        public string Faj47 { get; set; }
        public short? Faj471 { get; set; }
        public string Faj48 { get; set; }
        public string Faj49 { get; set; }
        public DateTime? Faj491 { get; set; }
        public string Faj50 { get; set; }
        public string Faj51 { get; set; }
        public DateTime? Faj511 { get; set; }
        public string Faj52 { get; set; }
        public string Faj53 { get; set; }
        public string Faj54 { get; set; }
        public string Faj55 { get; set; }
        public string Faj56 { get; set; }
        public short? Faj57 { get; set; }
        public short? Faj571 { get; set; }
        public short? Faj58 { get; set; }
        public decimal? Faj59 { get; set; }
        public decimal? Faj60 { get; set; }
        public string Faj61 { get; set; }
        public decimal? Faj62 { get; set; }
        public decimal? Faj63 { get; set; }
        public short? Faj64 { get; set; }
        public short? Faj65 { get; set; }
        public decimal? Faj66 { get; set; }
        public decimal? Faj67 { get; set; }
        public decimal? Faj68 { get; set; }
        public decimal? Faj69 { get; set; }
        public decimal? Faj70 { get; set; }
        public string Faj71 { get; set; }
        public decimal? Faj72 { get; set; }
        public short? Faj73 { get; set; }
        public short? Faj74 { get; set; }
        public short? Faj741 { get; set; }
        public short? Faj80 { get; set; }
        public decimal? Faj81 { get; set; }
        public decimal? Faj811 { get; set; }
        public short? Faj812 { get; set; }
        public string Faj813 { get; set; }
        public DateTime? Faj82 { get; set; }
        public string Faj83 { get; set; }
        public DateTime? Faj84 { get; set; }
        public string Faj85 { get; set; }
        public string Faj851 { get; set; }
        public decimal? Faj86 { get; set; }
        public decimal? Faj87 { get; set; }
        public DateTime? Faj88 { get; set; }
        public string Faj89 { get; set; }
        public string Faj90 { get; set; }
        public DateTime? Faj91 { get; set; }
        public string Faj92 { get; set; }
        public string Faj921 { get; set; }
        public DateTime? Faj100 { get; set; }
        public string Faj201 { get; set; }
        public short? Faj202 { get; set; }
        public decimal? Faj203 { get; set; }
        public decimal? Faj204 { get; set; }
        public decimal? Faj205 { get; set; }
        public decimal? Faj206 { get; set; }
        public string Faj207 { get; set; }
        public string Fajconf { get; set; }
        public string Fajuser { get; set; }
        public string Fajgrup { get; set; }
        public string Fajmodu { get; set; }
        public DateTime? Fajdate { get; set; }
        public decimal? Faj101 { get; set; }
        public decimal? Faj102 { get; set; }
        public decimal? Faj103 { get; set; }
        public decimal? Faj104 { get; set; }
        public string Faj105 { get; set; }
        public decimal? Faj106 { get; set; }
        public decimal? Faj107 { get; set; }
        public decimal? Faj108 { get; set; }
        public decimal? Faj109 { get; set; }
        public decimal? Faj110 { get; set; }
        public decimal? Faj111 { get; set; }
        public decimal? Faj112 { get; set; }
        public decimal? Faj113 { get; set; }
        public short? Faj114 { get; set; }
        public string Faj115 { get; set; }
        public string Faj531 { get; set; }
        public string Faj541 { get; set; }
        public string Faj551 { get; set; }
        public string Fajud01 { get; set; }
        public string Fajud02 { get; set; }
        public string Fajud03 { get; set; }
        public string Fajud04 { get; set; }
        public string Fajud05 { get; set; }
        public string Fajud06 { get; set; }
        public decimal? Fajud07 { get; set; }
        public decimal? Fajud08 { get; set; }
        public decimal? Fajud09 { get; set; }
        public int? Fajud10 { get; set; }
        public int? Fajud11 { get; set; }
        public int? Fajud12 { get; set; }
        public DateTime? Fajud13 { get; set; }
        public DateTime? Fajud14 { get; set; }
        public DateTime? Fajud15 { get; set; }
        public decimal Faj331 { get; set; }
        public decimal Faj681 { get; set; }
        public string Fajoriu { get; set; }
        public string Fajorig { get; set; }
        public string Faj93 { get; set; }
        public decimal Faj1012 { get; set; }
        public decimal Faj1022 { get; set; }
        public decimal Faj1062 { get; set; }
        public decimal Faj1072 { get; set; }
        public decimal Faj1082 { get; set; }
        public decimal Faj1412 { get; set; }
        public decimal Faj142 { get; set; }
        public string Faj143 { get; set; }
        public decimal? Faj144 { get; set; }
        public decimal Faj2032 { get; set; }
        public decimal Faj2042 { get; set; }
        public string Faj232 { get; set; }
        public string Faj242 { get; set; }
        public DateTime? Faj262 { get; set; }
        public string Faj272 { get; set; }
        public string Faj282 { get; set; }
        public short? Faj292 { get; set; }
        public short? Faj302 { get; set; }
        public decimal Faj312 { get; set; }
        public decimal Faj322 { get; set; }
        public decimal Faj3312 { get; set; }
        public decimal Faj332 { get; set; }
        public string Faj342 { get; set; }
        public decimal Faj352 { get; set; }
        public short? Faj362 { get; set; }
        public string Faj432 { get; set; }
        public short? Faj5712 { get; set; }
        public short? Faj572 { get; set; }
        public short? Faj582 { get; set; }
        public decimal Faj592 { get; set; }
        public decimal Faj602 { get; set; }
    }
}
