using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class FakFile
    {
        public string Fak00 { get; set; }
        public string Fak01 { get; set; }
        public string Fak02 { get; set; }
        public string Fak021 { get; set; }
        public string Fak022 { get; set; }
        public string Fak03 { get; set; }
        public string Fak04 { get; set; }
        public string Fak05 { get; set; }
        public string Fak06 { get; set; }
        public string Fak061 { get; set; }
        public string Fak07 { get; set; }
        public string Fak071 { get; set; }
        public string Fak08 { get; set; }
        public string Fak09 { get; set; }
        public string Fak10 { get; set; }
        public string Fak11 { get; set; }
        public string Fak12 { get; set; }
        public decimal? Fak13 { get; set; }
        public decimal? Fak14 { get; set; }
        public decimal? Fak141 { get; set; }
        public string Fak15 { get; set; }
        public decimal? Fak16 { get; set; }
        public short? Fak17 { get; set; }
        public short? Fak171 { get; set; }
        public string Fak18 { get; set; }
        public string Fak19 { get; set; }
        public string Fak20 { get; set; }
        public string Fak21 { get; set; }
        public string Fak22 { get; set; }
        public string Fak23 { get; set; }
        public string Fak24 { get; set; }
        public DateTime? Fak25 { get; set; }
        public DateTime? Fak26 { get; set; }
        public string Fak27 { get; set; }
        public string Fak28 { get; set; }
        public short? Fak29 { get; set; }
        public short? Fak30 { get; set; }
        public decimal? Fak31 { get; set; }
        public decimal? Fak32 { get; set; }
        public decimal? Fak33 { get; set; }
        public string Fak34 { get; set; }
        public decimal? Fak35 { get; set; }
        public short? Fak36 { get; set; }
        public string Fak37 { get; set; }
        public string Fak38 { get; set; }
        public string Fak39 { get; set; }
        public string Fak40 { get; set; }
        public string Fak41 { get; set; }
        public string Fak42 { get; set; }
        public short? Fak421 { get; set; }
        public short? Fak422 { get; set; }
        public short? Fak423 { get; set; }
        public string Fak43 { get; set; }
        public string Fak44 { get; set; }
        public string Fak45 { get; set; }
        public short? Fak451 { get; set; }
        public string Fak46 { get; set; }
        public short? Fak461 { get; set; }
        public DateTime? Fak462 { get; set; }
        public string Fak47 { get; set; }
        public short? Fak471 { get; set; }
        public string Fak48 { get; set; }
        public string Fak49 { get; set; }
        public string Fak50 { get; set; }
        public string Fak51 { get; set; }
        public DateTime? Fak511 { get; set; }
        public string Fak52 { get; set; }
        public string Fak53 { get; set; }
        public string Fak54 { get; set; }
        public string Fak55 { get; set; }
        public string Fak56 { get; set; }
        public short? Fak57 { get; set; }
        public short? Fak571 { get; set; }
        public short? Fak58 { get; set; }
        public decimal? Fak59 { get; set; }
        public decimal? Fak60 { get; set; }
        public string Fak61 { get; set; }
        public decimal? Fak62 { get; set; }
        public decimal? Fak63 { get; set; }
        public short? Fak64 { get; set; }
        public short? Fak65 { get; set; }
        public decimal? Fak66 { get; set; }
        public decimal? Fak67 { get; set; }
        public decimal? Fak68 { get; set; }
        public decimal? Fak69 { get; set; }
        public decimal? Fak70 { get; set; }
        public string Fak71 { get; set; }
        public decimal? Fak72 { get; set; }
        public short? Fak73 { get; set; }
        public short? Fak74 { get; set; }
        public string Fak90 { get; set; }
        public string Fak901 { get; set; }
        public string Fak91 { get; set; }
        public string Fak92 { get; set; }
        public string Fak207 { get; set; }
        public string Fakuser { get; set; }
        public string Fakgrup { get; set; }
        public string Fakmodu { get; set; }
        public DateTime? Fakdate { get; set; }
        public string Fak531 { get; set; }
        public string Fak541 { get; set; }
        public string Fak551 { get; set; }
        public string Fakud01 { get; set; }
        public string Fakud02 { get; set; }
        public string Fakud03 { get; set; }
        public string Fakud04 { get; set; }
        public string Fakud05 { get; set; }
        public string Fakud06 { get; set; }
        public decimal? Fakud07 { get; set; }
        public decimal? Fakud08 { get; set; }
        public decimal? Fakud09 { get; set; }
        public int? Fakud10 { get; set; }
        public int? Fakud11 { get; set; }
        public int? Fakud12 { get; set; }
        public DateTime? Fakud13 { get; set; }
        public DateTime? Fakud14 { get; set; }
        public DateTime? Fakud15 { get; set; }
        public string Fakoriu { get; set; }
        public string Fakorig { get; set; }
        public string Fak93 { get; set; }
        public decimal Fak1412 { get; set; }
        public decimal Fak142 { get; set; }
        public string Fak143 { get; set; }
        public decimal? Fak144 { get; set; }
        public string Fak232 { get; set; }
        public string Fak242 { get; set; }
        public DateTime? Fak262 { get; set; }
        public string Fak272 { get; set; }
        public string Fak282 { get; set; }
        public short? Fak292 { get; set; }
        public short? Fak302 { get; set; }
        public decimal Fak312 { get; set; }
        public decimal Fak322 { get; set; }
        public decimal Fak332 { get; set; }
        public string Fak342 { get; set; }
        public decimal Fak352 { get; set; }
        public short? Fak362 { get; set; }
        public short? Fak5712 { get; set; }
        public short? Fak572 { get; set; }
    }
}
