using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class FapFile
    {
        public string Fap01 { get; set; }
        public string Fap02 { get; set; }
        public string Fap021 { get; set; }
        public string Fap03 { get; set; }
        public DateTime Fap04 { get; set; }
        public string Fap05 { get; set; }
        public string Fap06 { get; set; }
        public short? Fap07 { get; set; }
        public decimal? Fap08 { get; set; }
        public decimal? Fap09 { get; set; }
        public decimal? Fap10 { get; set; }
        public decimal? Fap101 { get; set; }
        public decimal? Fap11 { get; set; }
        public string Fap12 { get; set; }
        public string Fap13 { get; set; }
        public string Fap14 { get; set; }
        public string Fap15 { get; set; }
        public string Fap16 { get; set; }
        public string Fap17 { get; set; }
        public string Fap18 { get; set; }
        public string Fap19 { get; set; }
        public short? Fap20 { get; set; }
        public short? Fap201 { get; set; }
        public short? Fap21 { get; set; }
        public decimal? Fap22 { get; set; }
        public decimal? Fap23 { get; set; }
        public string Fap24 { get; set; }
        public decimal? Fap25 { get; set; }
        public short? Fap26 { get; set; }
        public string Fap30 { get; set; }
        public short? Fap31 { get; set; }
        public decimal? Fap32 { get; set; }
        public decimal? Fap33 { get; set; }
        public decimal? Fap34 { get; set; }
        public decimal? Fap341 { get; set; }
        public decimal? Fap35 { get; set; }
        public decimal? Fap36 { get; set; }
        public decimal? Fap37 { get; set; }
        public string Fap38 { get; set; }
        public decimal? Fap39 { get; set; }
        public short? Fap40 { get; set; }
        public DateTime? Fap41 { get; set; }
        public string Fap42 { get; set; }
        public string Fap43 { get; set; }
        public string Fap44 { get; set; }
        public decimal? Fap45 { get; set; }
        public string Fap50 { get; set; }
        public short? Fap501 { get; set; }
        public string Fap51 { get; set; }
        public short? Fap52 { get; set; }
        public decimal? Fap53 { get; set; }
        public decimal? Fap54 { get; set; }
        public decimal? Fap55 { get; set; }
        public decimal? Fap56 { get; set; }
        public decimal? Fap57 { get; set; }
        public string Fap58 { get; set; }
        public string Fap59 { get; set; }
        public string Fap60 { get; set; }
        public string Fap61 { get; set; }
        public string Fap62 { get; set; }
        public string Fap63 { get; set; }
        public string Fap64 { get; set; }
        public string Fap65 { get; set; }
        public short? Fap66 { get; set; }
        public decimal? Fap661 { get; set; }
        public short? Fap67 { get; set; }
        public string Fap68 { get; set; }
        public short? Fap69 { get; set; }
        public decimal? Fap70 { get; set; }
        public decimal? Fap71 { get; set; }
        public decimal? Fap711 { get; set; }
        public decimal? Fap72 { get; set; }
        public decimal? Fap73 { get; set; }
        public decimal? Fap74 { get; set; }
        public string Fap75 { get; set; }
        public string Fap76 { get; set; }
        public string Fap77 { get; set; }
        public decimal? Fap78 { get; set; }
        public decimal? Fap79 { get; set; }
        public decimal? Fap80 { get; set; }
        public string Fap121 { get; set; }
        public string Fap131 { get; set; }
        public string Fap141 { get; set; }
        public string Fap581 { get; set; }
        public string Fap591 { get; set; }
        public string Fap601 { get; set; }
        public string Faplegal { get; set; }
        public string Fap052 { get; set; }
        public string Fap062 { get; set; }
        public short? Fap072 { get; set; }
        public decimal Fap082 { get; set; }
        public decimal Fap092 { get; set; }
        public decimal Fap1012 { get; set; }
        public decimal Fap112 { get; set; }
        public string Fap152 { get; set; }
        public string Fap162 { get; set; }
        public short? Fap212 { get; set; }
        public decimal Fap222 { get; set; }
        public decimal Fap232 { get; set; }
        public string Fap242 { get; set; }
        public decimal Fap252 { get; set; }
        public short? Fap262 { get; set; }
        public string Fap512 { get; set; }
        public short? Fap522 { get; set; }
        public decimal Fap532 { get; set; }
        public decimal Fap552 { get; set; }
        public decimal Fap562 { get; set; }
        public decimal Fap572 { get; set; }
        public string Fap612 { get; set; }
        public string Fap622 { get; set; }
        public decimal Fap6612 { get; set; }
        public short? Fap672 { get; set; }
        public string Fap772 { get; set; }
        public decimal Fap802 { get; set; }
        public decimal Fap542 { get; set; }
        public decimal Fap103 { get; set; }
        public DateTime? Fap042 { get; set; }
        public string Fap27 { get; set; }
        public string Fap81 { get; set; }
    }
}
