using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class IdhFile
    {
        public string Idh001 { get; set; }
        public short Idh0011 { get; set; }
        public string Idh002 { get; set; }
        public string Idh003 { get; set; }
        public string Idh004 { get; set; }
        public short? Idh005 { get; set; }
        public string Idh006 { get; set; }
        public string Idh007 { get; set; }
        public string Idh008 { get; set; }
        public string Idh009 { get; set; }
        public string Idh010 { get; set; }
        public string Idh011 { get; set; }
        public decimal? Idh012 { get; set; }
        public decimal? Idh013 { get; set; }
        public decimal? Idh014 { get; set; }
        public string Idh015 { get; set; }
        public DateTime? Idh016 { get; set; }
        public string Idh017 { get; set; }
        public short? Idh018 { get; set; }
        public string Idh019 { get; set; }
        public string Idh020 { get; set; }
        public string Idh021 { get; set; }
        public string Idh022 { get; set; }
        public decimal? Idh023 { get; set; }
        public decimal? Idh024 { get; set; }
        public decimal? Idh025 { get; set; }
        public decimal? Idh026 { get; set; }
        public decimal? Idh027 { get; set; }
        public string Idh028 { get; set; }
        public decimal? Idh029 { get; set; }
        public string Idh030 { get; set; }
        public string Idh031 { get; set; }
        public string Idh032 { get; set; }
        public string Idh033 { get; set; }
        public string Idh034 { get; set; }
        public string Idh035 { get; set; }
        public decimal? Idh036 { get; set; }
        public decimal? Idh037 { get; set; }
        public decimal? Idh038 { get; set; }
        public decimal? Idh039 { get; set; }
        public decimal? Idh040 { get; set; }
        public decimal? Idh041 { get; set; }
        public decimal? Idh042 { get; set; }
        public decimal? Idh043 { get; set; }
        public decimal? Idh044 { get; set; }
        public decimal? Idh045 { get; set; }
        public decimal? Idh046 { get; set; }
        public decimal? Idh047 { get; set; }
        public decimal? Idh048 { get; set; }
        public decimal? Idh049 { get; set; }
        public decimal? Idh050 { get; set; }
        public decimal? Idh051 { get; set; }
        public decimal? Idh052 { get; set; }
        public decimal? Idh053 { get; set; }
        public decimal? Idh054 { get; set; }
        public decimal? Idh055 { get; set; }
        public decimal? Idh056 { get; set; }
        public decimal? Idh057 { get; set; }
        public decimal? Idh058 { get; set; }
        public decimal? Idh059 { get; set; }
        public decimal? Idh060 { get; set; }
        public decimal? Idh061 { get; set; }
        public decimal? Idh062 { get; set; }
        public decimal? Idh063 { get; set; }
        public decimal? Idh064 { get; set; }
        public decimal? Idh065 { get; set; }
        public decimal? Idh066 { get; set; }
        public decimal? Idh067 { get; set; }
        public decimal? Idh068 { get; set; }
        public decimal? Idh069 { get; set; }
        public decimal? Idh070 { get; set; }
        public decimal? Idh071 { get; set; }
        public decimal? Idh072 { get; set; }
        public decimal? Idh073 { get; set; }
        public decimal? Idh074 { get; set; }
        public decimal? Idh075 { get; set; }
        public decimal? Idh076 { get; set; }
        public decimal? Idh077 { get; set; }
        public decimal? Idh078 { get; set; }
        public decimal? Idh079 { get; set; }
        public decimal? Idh080 { get; set; }
        public decimal? Idh081 { get; set; }
        public decimal? Idh082 { get; set; }
        public decimal? Idh083 { get; set; }
        public decimal? Idh084 { get; set; }
        public decimal? Idh085 { get; set; }
        public decimal? Idh086 { get; set; }
        public decimal? Idh087 { get; set; }
        public decimal? Idh088 { get; set; }
        public decimal? Idh089 { get; set; }
        public decimal? Idh090 { get; set; }
        public decimal? Idh091 { get; set; }
        public decimal? Idh092 { get; set; }
        public decimal? Idh093 { get; set; }
        public decimal? Idh094 { get; set; }
        public decimal? Idh095 { get; set; }
        public string Idh096 { get; set; }
        public string Idh097 { get; set; }
        public string Idh098 { get; set; }
        public short? Idh099 { get; set; }
        public decimal? Idh101 { get; set; }
        public string Idh102 { get; set; }
        public string Idh103 { get; set; }
        public string Idh104 { get; set; }
        public string Idh105 { get; set; }
        public decimal? Idh106 { get; set; }
        public string Idh107 { get; set; }
        public DateTime? Idh108 { get; set; }
        public decimal? Idh109 { get; set; }
        public string Idh110 { get; set; }
        public string Idh111 { get; set; }
        public string Idh112 { get; set; }
        public decimal? Idh113 { get; set; }
        public decimal? Idh114 { get; set; }
        public decimal? Idh115 { get; set; }
        public decimal? Idh116 { get; set; }
        public decimal? Idh117 { get; set; }
        public decimal? Idh118 { get; set; }
        public decimal? Idh119 { get; set; }
        public decimal? Idh120 { get; set; }
        public decimal? Idh121 { get; set; }
        public decimal? Idh122 { get; set; }
        public decimal? Idh123 { get; set; }
        public decimal? Idh124 { get; set; }
        public decimal? Idh125 { get; set; }
        public decimal? Idh126 { get; set; }
        public decimal? Idh127 { get; set; }
        public decimal? Idh128 { get; set; }
        public decimal? Idh129 { get; set; }
        public decimal? Idh130 { get; set; }
        public decimal? Idh131 { get; set; }
        public decimal? Idh132 { get; set; }
        public decimal? Idh133 { get; set; }
        public decimal? Idh134 { get; set; }
        public decimal? Idh135 { get; set; }
        public decimal? Idh136 { get; set; }
        public decimal? Idh137 { get; set; }
        public decimal? Idh138 { get; set; }
        public decimal? Idh139 { get; set; }
        public decimal? Idh140 { get; set; }
        public decimal? Idh141 { get; set; }
        public decimal? Idh142 { get; set; }
        public decimal? Idh143 { get; set; }
        public string Idh144 { get; set; }
        public string Idhplant { get; set; }
        public string Idhlegal { get; set; }
        public string Idh145 { get; set; }
    }
}
