using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class ImaaFile
    {
        public string Imaa00 { get; set; }
        public string Imaano { get; set; }
        public string Imaa011 { get; set; }
        public string Imaa01 { get; set; }
        public string Imaa02 { get; set; }
        public string Imaa021 { get; set; }
        public string Imaa03 { get; set; }
        public string Imaa04 { get; set; }
        public string Imaa05 { get; set; }
        public string Imaa06 { get; set; }
        public string Imaa07 { get; set; }
        public string Imaa08 { get; set; }
        public string Imaa09 { get; set; }
        public string Imaa10 { get; set; }
        public string Imaa11 { get; set; }
        public string Imaa12 { get; set; }
        public string Imaa13 { get; set; }
        public string Imaa14 { get; set; }
        public string Imaa15 { get; set; }
        public short? Imaa16 { get; set; }
        public string Imaa17 { get; set; }
        public decimal? Imaa17Fac { get; set; }
        public decimal? Imaa18 { get; set; }
        public string Imaa19 { get; set; }
        public decimal? Imaa20 { get; set; }
        public string Imaa21 { get; set; }
        public decimal? Imaa22 { get; set; }
        public string Imaa23 { get; set; }
        public string Imaa24 { get; set; }
        public string Imaa25 { get; set; }
        public decimal Imaa26 { get; set; }
        public decimal Imaa261 { get; set; }
        public decimal Imaa262 { get; set; }
        public decimal? Imaa27 { get; set; }
        public decimal? Imaa271 { get; set; }
        public decimal? Imaa28 { get; set; }
        public DateTime? Imaa29 { get; set; }
        public DateTime? Imaa30 { get; set; }
        public string Imaa31 { get; set; }
        public decimal? Imaa31Fac { get; set; }
        public decimal? Imaa32 { get; set; }
        public decimal? Imaa33 { get; set; }
        public string Imaa34 { get; set; }
        public string Imaa35 { get; set; }
        public string Imaa36 { get; set; }
        public string Imaa37 { get; set; }
        public decimal? Imaa38 { get; set; }
        public string Imaa39 { get; set; }
        public decimal? Imaa40 { get; set; }
        public decimal? Imaa41 { get; set; }
        public string Imaa42 { get; set; }
        public string Imaa43 { get; set; }
        public string Imaa44 { get; set; }
        public decimal? Imaa44Fac { get; set; }
        public decimal? Imaa45 { get; set; }
        public decimal? Imaa46 { get; set; }
        public decimal? Imaa47 { get; set; }
        public decimal? Imaa48 { get; set; }
        public decimal? Imaa49 { get; set; }
        public decimal? Imaa491 { get; set; }
        public decimal? Imaa50 { get; set; }
        public decimal? Imaa51 { get; set; }
        public decimal? Imaa52 { get; set; }
        public decimal? Imaa53 { get; set; }
        public decimal? Imaa531 { get; set; }
        public DateTime? Imaa532 { get; set; }
        public string Imaa54 { get; set; }
        public string Imaa55 { get; set; }
        public decimal? Imaa55Fac { get; set; }
        public decimal? Imaa56 { get; set; }
        public decimal? Imaa561 { get; set; }
        public decimal? Imaa562 { get; set; }
        public short? Imaa57 { get; set; }
        public string Imaa571 { get; set; }
        public decimal? Imaa58 { get; set; }
        public decimal? Imaa59 { get; set; }
        public decimal? Imaa60 { get; set; }
        public decimal? Imaa61 { get; set; }
        public decimal? Imaa62 { get; set; }
        public string Imaa63 { get; set; }
        public decimal? Imaa63Fac { get; set; }
        public decimal? Imaa64 { get; set; }
        public decimal? Imaa641 { get; set; }
        public decimal? Imaa65 { get; set; }
        public decimal? Imaa66 { get; set; }
        public string Imaa67 { get; set; }
        public decimal? Imaa68 { get; set; }
        public decimal? Imaa69 { get; set; }
        public string Imaa70 { get; set; }
        public short? Imaa71 { get; set; }
        public decimal? Imaa72 { get; set; }
        public DateTime? Imaa73 { get; set; }
        public DateTime? Imaa74 { get; set; }
        public string Imaa86 { get; set; }
        public decimal? Imaa86Fac { get; set; }
        public string Imaa87 { get; set; }
        public decimal? Imaa871 { get; set; }
        public string Imaa872 { get; set; }
        public decimal? Imaa873 { get; set; }
        public string Imaa874 { get; set; }
        public decimal? Imaa88 { get; set; }
        public DateTime? Imaa881 { get; set; }
        public short? Imaa89 { get; set; }
        public short? Imaa90 { get; set; }
        public decimal? Imaa91 { get; set; }
        public string Imaa92 { get; set; }
        public string Imaa93 { get; set; }
        public string Imaa94 { get; set; }
        public decimal? Imaa95 { get; set; }
        public string Imaa75 { get; set; }
        public string Imaa76 { get; set; }
        public decimal? Imaa77 { get; set; }
        public short? Imaa78 { get; set; }
        public short? Imaa79 { get; set; }
        public short? Imaa80 { get; set; }
        public short? Imaa81 { get; set; }
        public short? Imaa82 { get; set; }
        public short? Imaa83 { get; set; }
        public short? Imaa84 { get; set; }
        public short? Imaa85 { get; set; }
        public string Imaa851 { get; set; }
        public string Imaa852 { get; set; }
        public string Imaa853 { get; set; }
        public short? Imaa96 { get; set; }
        public short? Imaa97 { get; set; }
        public decimal? Imaa98 { get; set; }
        public decimal? Imaa99 { get; set; }
        public string Imaa100 { get; set; }
        public string Imaa101 { get; set; }
        public string Imaa102 { get; set; }
        public string Imaa103 { get; set; }
        public decimal? Imaa104 { get; set; }
        public string Imaa105 { get; set; }
        public string Imaa106 { get; set; }
        public string Imaa107 { get; set; }
        public string Imaa108 { get; set; }
        public string Imaa109 { get; set; }
        public string Imaa110 { get; set; }
        public string Imaa111 { get; set; }
        public decimal? Imaa121 { get; set; }
        public decimal? Imaa122 { get; set; }
        public decimal? Imaa123 { get; set; }
        public decimal? Imaa124 { get; set; }
        public decimal? Imaa125 { get; set; }
        public decimal? Imaa126 { get; set; }
        public decimal? Imaa127 { get; set; }
        public decimal? Imaa128 { get; set; }
        public decimal? Imaa129 { get; set; }
        public string Imaa130 { get; set; }
        public string Imaa131 { get; set; }
        public string Imaa132 { get; set; }
        public string Imaa133 { get; set; }
        public string Imaa134 { get; set; }
        public string Imaa135 { get; set; }
        public string Imaa136 { get; set; }
        public string Imaa137 { get; set; }
        public string Imaa138 { get; set; }
        public string Imaa139 { get; set; }
        public string Imaa140 { get; set; }
        public string Imaa141 { get; set; }
        public short? Imaa142 { get; set; }
        public short? Imaa143 { get; set; }
        public string Imaa144 { get; set; }
        public string Imaa145 { get; set; }
        public string Imaa146 { get; set; }
        public string Imaa147 { get; set; }
        public short? Imaa148 { get; set; }
        public DateTime? Imaa901 { get; set; }
        public DateTime? Imaa902 { get; set; }
        public string Imaa903 { get; set; }
        public string Imaa904 { get; set; }
        public string Imaa905 { get; set; }
        public string Imaa906 { get; set; }
        public string Imaa907 { get; set; }
        public string Imaa908 { get; set; }
        public short? Imaa909 { get; set; }
        public string Imaa910 { get; set; }
        public string Imaaacti { get; set; }
        public string Imaauser { get; set; }
        public string Imaagrup { get; set; }
        public string Imaamodu { get; set; }
        public DateTime? Imaadate { get; set; }
        public string Imaaag { get; set; }
        public string Imaaag1 { get; set; }
        public string Imaaud01 { get; set; }
        public string Imaaud02 { get; set; }
        public string Imaaud03 { get; set; }
        public string Imaaud04 { get; set; }
        public string Imaaud05 { get; set; }
        public string Imaaud06 { get; set; }
        public decimal? Imaaud07 { get; set; }
        public decimal? Imaaud08 { get; set; }
        public decimal? Imaaud09 { get; set; }
        public int? Imaaud10 { get; set; }
        public int? Imaaud11 { get; set; }
        public int? Imaaud12 { get; set; }
        public DateTime? Imaaud13 { get; set; }
        public DateTime? Imaaud14 { get; set; }
        public DateTime? Imaaud15 { get; set; }
        public string Imaa1001 { get; set; }
        public string Imaa1002 { get; set; }
        public string Imaa1003 { get; set; }
        public string Imaa1004 { get; set; }
        public string Imaa1005 { get; set; }
        public string Imaa1006 { get; set; }
        public string Imaa1007 { get; set; }
        public string Imaa1008 { get; set; }
        public string Imaa1009 { get; set; }
        public string Imaa1010 { get; set; }
        public decimal? Imaa1011 { get; set; }
        public DateTime? Imaa1012 { get; set; }
        public DateTime? Imaa1013 { get; set; }
        public string Imaa1014 { get; set; }
        public DateTime? Imaa1015 { get; set; }
        public string Imaa1016 { get; set; }
        public decimal? Imaa1017 { get; set; }
        public decimal? Imaa1018 { get; set; }
        public decimal? Imaa1019 { get; set; }
        public decimal? Imaa1020 { get; set; }
        public decimal? Imaa1021 { get; set; }
        public decimal? Imaa1022 { get; set; }
        public decimal? Imaa1023 { get; set; }
        public decimal? Imaa1024 { get; set; }
        public decimal? Imaa1025 { get; set; }
        public decimal? Imaa1026 { get; set; }
        public decimal? Imaa1027 { get; set; }
        public decimal? Imaa1028 { get; set; }
        public string Imaa1029 { get; set; }
        public string Imaa911 { get; set; }
        public decimal? Imaa912 { get; set; }
        public string Imaa913 { get; set; }
        public string Imaa914 { get; set; }
        public string Imaa391 { get; set; }
        public string Imaa1321 { get; set; }
        public string Imaa915 { get; set; }
        public string Imaa918 { get; set; }
        public string Imaa919 { get; set; }
        public string Imaa920 { get; set; }
        public string Imaa921 { get; set; }
        public string Imaa922 { get; set; }
        public string Imaa923 { get; set; }
        public string Imaa924 { get; set; }
        public string Imaa925 { get; set; }
        public decimal? Imaa601 { get; set; }
        public string Imaa926 { get; set; }
        public string Imaaoriu { get; set; }
        public string Imaaorig { get; set; }
        public decimal? Imaa153 { get; set; }
        public string Imaa120 { get; set; }
        public decimal Imaa022 { get; set; }
        public string Imaa251 { get; set; }
        public string Imaaicd01 { get; set; }
        public string Imaaicd02 { get; set; }
        public string Imaaicd03 { get; set; }
        public string Imaaicd04 { get; set; }
        public string Imaaicd05 { get; set; }
        public string Imaaicd06 { get; set; }
        public string Imaaicd07 { get; set; }
        public string Imaaicd08 { get; set; }
        public string Imaaicd09 { get; set; }
        public string Imaaicd10 { get; set; }
        public string Imaaicd11 { get; set; }
        public decimal? Imaaicd12 { get; set; }
        public string Imaaicd13 { get; set; }
        public decimal Imaaicd14 { get; set; }
        public decimal Imaaicd15 { get; set; }
        public string Imaaicd16 { get; set; }
        public string Imaa159 { get; set; }
        public string Imaa1916 { get; set; }
        public string TaImaa002 { get; set; }
        public string TaImaa004 { get; set; }
    }
}
