using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class ImaFile
    {
        public string Ima01 { get; set; }
        public string Ima02 { get; set; }
        public string Ima021 { get; set; }
        public string Ima03 { get; set; }
        public string Ima04 { get; set; }
        public string Ima05 { get; set; }
        public string Ima06 { get; set; }
        public string Ima07 { get; set; }
        public string Ima08 { get; set; }
        public string Ima09 { get; set; }
        public string Ima10 { get; set; }
        public string Ima11 { get; set; }
        public string Ima12 { get; set; }
        public string Ima13 { get; set; }
        public string Ima14 { get; set; }
        public string Ima15 { get; set; }
        public short? Ima16 { get; set; }
        public string Ima17 { get; set; }
        public decimal? Ima17Fac { get; set; }
        public decimal? Ima18 { get; set; }
        public string Ima19 { get; set; }
        public decimal? Ima20 { get; set; }
        public string Ima21 { get; set; }
        public decimal? Ima22 { get; set; }
        public string Ima23 { get; set; }
        public string Ima24 { get; set; }
        public string Ima25 { get; set; }
        public decimal? Ima26 { get; set; }
        public decimal? Ima261 { get; set; }
        public decimal? Ima262 { get; set; }
        public decimal? Ima27 { get; set; }
        public decimal? Ima271 { get; set; }
        public decimal? Ima28 { get; set; }
        public DateTime? Ima29 { get; set; }
        public DateTime? Ima30 { get; set; }
        public string Ima31 { get; set; }
        public decimal? Ima31Fac { get; set; }
        public decimal? Ima32 { get; set; }
        public decimal? Ima33 { get; set; }
        public string Ima34 { get; set; }
        public string Ima35 { get; set; }
        public string Ima36 { get; set; }
        public string Ima37 { get; set; }
        public decimal? Ima38 { get; set; }
        public string Ima39 { get; set; }
        public decimal? Ima40 { get; set; }
        public decimal? Ima41 { get; set; }
        public string Ima42 { get; set; }
        public string Ima43 { get; set; }
        public string Ima44 { get; set; }
        public decimal? Ima44Fac { get; set; }
        public decimal? Ima45 { get; set; }
        public decimal? Ima46 { get; set; }
        public decimal? Ima47 { get; set; }
        public decimal? Ima48 { get; set; }
        public decimal? Ima49 { get; set; }
        public decimal? Ima491 { get; set; }
        public decimal? Ima50 { get; set; }
        public decimal? Ima51 { get; set; }
        public decimal? Ima52 { get; set; }
        public decimal? Ima53 { get; set; }
        public decimal? Ima531 { get; set; }
        public DateTime? Ima532 { get; set; }
        public string Ima54 { get; set; }
        public string Ima55 { get; set; }
        public decimal? Ima55Fac { get; set; }
        public decimal? Ima56 { get; set; }
        public decimal? Ima561 { get; set; }
        public decimal? Ima562 { get; set; }
        public short? Ima57 { get; set; }
        public string Ima571 { get; set; }
        public decimal? Ima58 { get; set; }
        public decimal? Ima59 { get; set; }
        public decimal? Ima60 { get; set; }
        public decimal? Ima61 { get; set; }
        public decimal? Ima62 { get; set; }
        public string Ima63 { get; set; }
        public decimal? Ima63Fac { get; set; }
        public decimal? Ima64 { get; set; }
        public decimal? Ima641 { get; set; }
        public decimal? Ima65 { get; set; }
        public decimal? Ima66 { get; set; }
        public string Ima67 { get; set; }
        public decimal? Ima68 { get; set; }
        public decimal? Ima69 { get; set; }
        public string Ima70 { get; set; }
        public short? Ima71 { get; set; }
        public decimal? Ima72 { get; set; }
        public DateTime? Ima73 { get; set; }
        public DateTime? Ima74 { get; set; }
        public string Ima86 { get; set; }
        public decimal? Ima86Fac { get; set; }
        public string Ima87 { get; set; }
        public decimal? Ima871 { get; set; }
        public string Ima872 { get; set; }
        public decimal? Ima873 { get; set; }
        public string Ima874 { get; set; }
        public decimal? Ima88 { get; set; }
        public DateTime? Ima881 { get; set; }
        public short? Ima89 { get; set; }
        public short? Ima90 { get; set; }
        public decimal? Ima91 { get; set; }
        public string Ima92 { get; set; }
        public string Ima93 { get; set; }
        public string Ima94 { get; set; }
        public decimal? Ima95 { get; set; }
        public string Ima75 { get; set; }
        public string Ima76 { get; set; }
        public decimal? Ima77 { get; set; }
        public short? Ima78 { get; set; }
        public short? Ima79 { get; set; }
        public short? Ima80 { get; set; }
        public short? Ima81 { get; set; }
        public short? Ima82 { get; set; }
        public short? Ima83 { get; set; }
        public short? Ima84 { get; set; }
        public short? Ima85 { get; set; }
        public string Ima851 { get; set; }
        public string Ima852 { get; set; }
        public string Ima853 { get; set; }
        public short? Ima96 { get; set; }
        public short? Ima97 { get; set; }
        public decimal? Ima98 { get; set; }
        public decimal? Ima99 { get; set; }
        public string Ima100 { get; set; }
        public string Ima101 { get; set; }
        public string Ima102 { get; set; }
        public string Ima103 { get; set; }
        public decimal? Ima104 { get; set; }
        public string Ima105 { get; set; }
        public string Ima106 { get; set; }
        public string Ima107 { get; set; }
        public string Ima108 { get; set; }
        public string Ima109 { get; set; }
        public string Ima110 { get; set; }
        public string Ima111 { get; set; }
        public decimal? Ima121 { get; set; }
        public decimal? Ima122 { get; set; }
        public decimal? Ima123 { get; set; }
        public decimal? Ima124 { get; set; }
        public decimal? Ima125 { get; set; }
        public decimal? Ima126 { get; set; }
        public decimal? Ima127 { get; set; }
        public decimal? Ima128 { get; set; }
        public decimal? Ima129 { get; set; }
        public string Ima130 { get; set; }
        public string Ima131 { get; set; }
        public string Ima132 { get; set; }
        public string Ima133 { get; set; }
        public string Ima134 { get; set; }
        public string Ima135 { get; set; }
        public string Ima136 { get; set; }
        public string Ima137 { get; set; }
        public string Ima138 { get; set; }
        public string Ima139 { get; set; }
        public string Ima140 { get; set; }
        public string Ima141 { get; set; }
        public short? Ima142 { get; set; }
        public short? Ima143 { get; set; }
        public string Ima144 { get; set; }
        public string Ima145 { get; set; }
        public string Ima146 { get; set; }
        public string Ima147 { get; set; }
        public short? Ima148 { get; set; }
        public DateTime? Ima901 { get; set; }
        public DateTime? Ima902 { get; set; }
        public string Ima903 { get; set; }
        public string Ima904 { get; set; }
        public string Ima905 { get; set; }
        public string Ima906 { get; set; }
        public string Ima907 { get; set; }
        public string Ima908 { get; set; }
        public short? Ima909 { get; set; }
        public string Ima910 { get; set; }
        public string Imaacti { get; set; }
        public string Imauser { get; set; }
        public string Imagrup { get; set; }
        public string Imamodu { get; set; }
        public DateTime? Imadate { get; set; }
        public string Imaag { get; set; }
        public string Imaag1 { get; set; }
        public string Imaud01 { get; set; }
        public string Imaud02 { get; set; }
        public string Imaud03 { get; set; }
        public string Imaud04 { get; set; }
        public string Imaud05 { get; set; }
        public string Imaud06 { get; set; }
        public decimal? Imaud07 { get; set; }
        public decimal? Imaud08 { get; set; }
        public decimal? Imaud09 { get; set; }
        public int? Imaud10 { get; set; }
        public int? Imaud11 { get; set; }
        public int? Imaud12 { get; set; }
        public DateTime? Imaud13 { get; set; }
        public DateTime? Imaud14 { get; set; }
        public DateTime? Imaud15 { get; set; }
        public string Ima1001 { get; set; }
        public string Ima1002 { get; set; }
        public string Ima1003 { get; set; }
        public string Ima1004 { get; set; }
        public string Ima1005 { get; set; }
        public string Ima1006 { get; set; }
        public string Ima1007 { get; set; }
        public string Ima1008 { get; set; }
        public string Ima1009 { get; set; }
        public string Ima1010 { get; set; }
        public decimal? Ima1011 { get; set; }
        public DateTime? Ima1012 { get; set; }
        public DateTime? Ima1013 { get; set; }
        public string Ima1014 { get; set; }
        public DateTime? Ima1015 { get; set; }
        public string Ima1016 { get; set; }
        public decimal? Ima1017 { get; set; }
        public decimal? Ima1018 { get; set; }
        public decimal? Ima1019 { get; set; }
        public decimal? Ima1020 { get; set; }
        public decimal? Ima1021 { get; set; }
        public decimal? Ima1022 { get; set; }
        public decimal? Ima1023 { get; set; }
        public decimal? Ima1024 { get; set; }
        public decimal? Ima1025 { get; set; }
        public decimal? Ima1026 { get; set; }
        public decimal? Ima1027 { get; set; }
        public decimal? Ima1028 { get; set; }
        public string Ima1029 { get; set; }
        public string Ima911 { get; set; }
        public decimal? Ima912 { get; set; }
        public string Ima913 { get; set; }
        public string Ima914 { get; set; }
        public string Ima391 { get; set; }
        public string Ima1321 { get; set; }
        public string Ima1911 { get; set; }
        public string Ima1912 { get; set; }
        public decimal? Ima1913 { get; set; }
        public string Ima1914 { get; set; }
        public string Ima1915 { get; set; }
        public string Ima1916 { get; set; }
        public string Ima1919 { get; set; }
        public DateTime? Ima1401 { get; set; }
        public string Ima915 { get; set; }
        public string Ima916 { get; set; }
        public int? Ima917 { get; set; }
        public string Ima150 { get; set; }
        public string Ima151 { get; set; }
        public string Ima152 { get; set; }
        public string Ima918 { get; set; }
        public string Ima919 { get; set; }
        public string Ima920 { get; set; }
        public string Ima921 { get; set; }
        public string Ima922 { get; set; }
        public string Ima923 { get; set; }
        public string Ima924 { get; set; }
        public string Ima925 { get; set; }
        public decimal? Ima601 { get; set; }
        public decimal? Ima153 { get; set; }
        public string Ima926 { get; set; }
        public string Ima154 { get; set; }
        public string Ima155 { get; set; }
        public string Ima149 { get; set; }
        public string Ima1491 { get; set; }
        public string Imaoriu { get; set; }
        public string Imaorig { get; set; }
        public DateTime? Ima9021 { get; set; }
        public decimal Ima022 { get; set; }
        public string Ima251 { get; set; }
        public string Ima940 { get; set; }
        public string Ima941 { get; set; }
        public string Ima156 { get; set; }
        public string Ima157 { get; set; }
        public string Ima158 { get; set; }
        public string Ima927 { get; set; }
        public string Ima120 { get; set; }
        public decimal? TaIma001 { get; set; }
        public string Ima159 { get; set; }
        public string TaIma002 { get; set; }
        public string TaIma003 { get; set; }
        public string TaIma004 { get; set; }
    }
}
