using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class ImzFile
    {
        public string Imz01 { get; set; }
        public string Imz02 { get; set; }
        public string Imz03 { get; set; }
        public string Imz04 { get; set; }
        public string Imz07 { get; set; }
        public string Imz08 { get; set; }
        public string Imz09 { get; set; }
        public string Imz10 { get; set; }
        public string Imz11 { get; set; }
        public string Imz12 { get; set; }
        public string Imz14 { get; set; }
        public string Imz15 { get; set; }
        public string Imz17 { get; set; }
        public string Imz19 { get; set; }
        public string Imz21 { get; set; }
        public string Imz23 { get; set; }
        public string Imz24 { get; set; }
        public string Imz25 { get; set; }
        public decimal? Imz27 { get; set; }
        public decimal? Imz28 { get; set; }
        public string Imz31 { get; set; }
        public decimal? Imz31Fac { get; set; }
        public string Imz34 { get; set; }
        public string Imz35 { get; set; }
        public string Imz36 { get; set; }
        public string Imz37 { get; set; }
        public decimal? Imz38 { get; set; }
        public string Imz39 { get; set; }
        public string Imz42 { get; set; }
        public string Imz43 { get; set; }
        public string Imz44 { get; set; }
        public decimal? Imz44Fac { get; set; }
        public decimal? Imz45 { get; set; }
        public decimal? Imz46 { get; set; }
        public decimal? Imz47 { get; set; }
        public decimal? Imz48 { get; set; }
        public decimal? Imz49 { get; set; }
        public decimal? Imz491 { get; set; }
        public decimal? Imz50 { get; set; }
        public decimal? Imz51 { get; set; }
        public decimal? Imz52 { get; set; }
        public string Imz54 { get; set; }
        public string Imz55 { get; set; }
        public decimal? Imz55Fac { get; set; }
        public decimal? Imz56 { get; set; }
        public decimal? Imz561 { get; set; }
        public decimal? Imz562 { get; set; }
        public string Imz571 { get; set; }
        public decimal? Imz59 { get; set; }
        public decimal? Imz60 { get; set; }
        public decimal? Imz61 { get; set; }
        public decimal? Imz62 { get; set; }
        public string Imz63 { get; set; }
        public decimal? Imz63Fac { get; set; }
        public decimal? Imz64 { get; set; }
        public decimal? Imz641 { get; set; }
        public decimal? Imz65 { get; set; }
        public decimal? Imz66 { get; set; }
        public string Imz67 { get; set; }
        public decimal? Imz68 { get; set; }
        public decimal? Imz69 { get; set; }
        public string Imz70 { get; set; }
        public short? Imz71 { get; set; }
        public string Imz86 { get; set; }
        public decimal? Imz86Fac { get; set; }
        public string Imz87 { get; set; }
        public decimal? Imz871 { get; set; }
        public string Imz872 { get; set; }
        public decimal? Imz873 { get; set; }
        public string Imz874 { get; set; }
        public decimal? Imz88 { get; set; }
        public short? Imz89 { get; set; }
        public short? Imz90 { get; set; }
        public string Imz94 { get; set; }
        public decimal? Imz99 { get; set; }
        public string Imz100 { get; set; }
        public string Imz101 { get; set; }
        public string Imz102 { get; set; }
        public string Imz103 { get; set; }
        public string Imz105 { get; set; }
        public string Imz106 { get; set; }
        public string Imz107 { get; set; }
        public string Imz108 { get; set; }
        public string Imz109 { get; set; }
        public string Imz110 { get; set; }
        public string Imz130 { get; set; }
        public string Imz131 { get; set; }
        public string Imz132 { get; set; }
        public string Imz133 { get; set; }
        public string Imz134 { get; set; }
        public string Imz147 { get; set; }
        public short? Imz148 { get; set; }
        public string Imz903 { get; set; }
        public string Imzacti { get; set; }
        public string Imzuser { get; set; }
        public string Imzgrup { get; set; }
        public string Imzmodu { get; set; }
        public DateTime? Imzdate { get; set; }
        public string Imz906 { get; set; }
        public string Imz907 { get; set; }
        public string Imz908 { get; set; }
        public short? Imz909 { get; set; }
        public string Imz911 { get; set; }
        public string Imz136 { get; set; }
        public string Imz137 { get; set; }
        public string Imz391 { get; set; }
        public string Imz1321 { get; set; }
        public string Imz72 { get; set; }
        public string Imz150 { get; set; }
        public string Imz152 { get; set; }
        public string Imzud01 { get; set; }
        public string Imzud02 { get; set; }
        public string Imzud03 { get; set; }
        public string Imzud04 { get; set; }
        public string Imzud05 { get; set; }
        public string Imzud06 { get; set; }
        public decimal? Imzud07 { get; set; }
        public decimal? Imzud08 { get; set; }
        public decimal? Imzud09 { get; set; }
        public int? Imzud10 { get; set; }
        public int? Imzud11 { get; set; }
        public int? Imzud12 { get; set; }
        public DateTime? Imzud13 { get; set; }
        public DateTime? Imzud14 { get; set; }
        public DateTime? Imzud15 { get; set; }
        public decimal? Imz601 { get; set; }
        public decimal? Imz153 { get; set; }
        public string Imz926 { get; set; }
        public string Imz73 { get; set; }
        public string Imz731 { get; set; }
        public string Imzicd01 { get; set; }
        public string Imzicd02 { get; set; }
        public string Imzicd03 { get; set; }
        public string Imzicd04 { get; set; }
        public string Imzicd05 { get; set; }
        public string Imzicd06 { get; set; }
        public string Imzicd07 { get; set; }
        public string Imzicd08 { get; set; }
        public string Imzicd09 { get; set; }
        public string Imzicd10 { get; set; }
        public decimal? Imzicd12 { get; set; }
        public string Imzicd79 { get; set; }
        public string Imzoriu { get; set; }
        public string Imzorig { get; set; }
        public string Imz918 { get; set; }
        public string Imz919 { get; set; }
        public string Imz920 { get; set; }
        public string Imz921 { get; set; }
        public string Imz922 { get; set; }
        public string Imz923 { get; set; }
        public string Imz924 { get; set; }
        public string Imz925 { get; set; }
        public string Imzicd13 { get; set; }
        public string Imz156 { get; set; }
        public string Imz157 { get; set; }
        public string Imz158 { get; set; }
        public decimal Imz022 { get; set; }
        public string Imz251 { get; set; }
        public decimal Imzicd14 { get; set; }
        public decimal Imzicd15 { get; set; }
        public string Imzicd16 { get; set; }
        public string Imz159 { get; set; }
    }
}
