using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OazFile
    {
        public string Oaz00 { get; set; }
        public string Oaz01 { get; set; }
        public string Oaz02 { get; set; }
        public string Oaz02p { get; set; }
        public string Oaz02b { get; set; }
        public string Oaz03 { get; set; }
        public string Oaz04 { get; set; }
        public string Oaz05 { get; set; }
        public string Oaz06 { get; set; }
        public string Oaz07 { get; set; }
        public string Oaz08 { get; set; }
        public DateTime? Oaz09 { get; set; }
        public string Oaz101 { get; set; }
        public string Oaz102 { get; set; }
        public string Oaz103 { get; set; }
        public string Oaz104 { get; set; }
        public string Oaz105 { get; set; }
        public string Oaz11 { get; set; }
        public string Oaz121 { get; set; }
        public string Oaz122 { get; set; }
        public string Oaz123 { get; set; }
        public string Oaz131 { get; set; }
        public string Oaz132 { get; set; }
        public string Oaz133 { get; set; }
        public string Oaz141 { get; set; }
        public string Oaz142 { get; set; }
        public short? Oaz151 { get; set; }
        public short? Oaz152 { get; set; }
        public short? Oaz153 { get; set; }
        public short? Oaz154 { get; set; }
        public short? Oaz155 { get; set; }
        public short? Oaz156 { get; set; }
        public short? Oaz161 { get; set; }
        public short? Oaz162 { get; set; }
        public short? Oaz163 { get; set; }
        public short? Oaz164 { get; set; }
        public short? Oaz165 { get; set; }
        public short? Oaz166 { get; set; }
        public string Oaz171 { get; set; }
        public string Oaz172 { get; set; }
        public string Oaz173 { get; set; }
        public string Oaz174 { get; set; }
        public string Oaz175 { get; set; }
        public string Oaz176 { get; set; }
        public string Oaz181 { get; set; }
        public string Oaz182 { get; set; }
        public string Oaz183 { get; set; }
        public string Oaz184 { get; set; }
        public decimal? Oaz185 { get; set; }
        public string Oaz186 { get; set; }
        public string Oaz19 { get; set; }
        public short? Oaz201 { get; set; }
        public string Oaz202 { get; set; }
        public string Oaz203 { get; set; }
        public string Oaz204 { get; set; }
        public string Oaz205 { get; set; }
        public string Oaz206 { get; set; }
        public short? Oaz207 { get; set; }
        public short? Oaz208 { get; set; }
        public short? Oaz209 { get; set; }
        public string Oaz211 { get; set; }
        public string Oaz212 { get; set; }
        public short? Oaz213 { get; set; }
        public short? Oaz214 { get; set; }
        public short? Oaz215 { get; set; }
        public short? Oaz216 { get; set; }
        public short? Oaz217 { get; set; }
        public short? Oaz218 { get; set; }
        public short? Oaz219 { get; set; }
        public string Oaz22 { get; set; }
        public string Oaz23 { get; set; }
        public string Oaz24 { get; set; }
        public short? Oaz25 { get; set; }
        public string Oaz31 { get; set; }
        public string Oaz32 { get; set; }
        public string Oaz41 { get; set; }
        public string Oaz42 { get; set; }
        public string Oaz43 { get; set; }
        public string Oaz44 { get; set; }
        public string Oaz45 { get; set; }
        public string Oaz46 { get; set; }
        public string Oaz51 { get; set; }
        public string Oaz52 { get; set; }
        public string Oaz61 { get; set; }
        public string Oaz62 { get; set; }
        public string Oaz63 { get; set; }
        public string Oaz64 { get; set; }
        public string Oaz65 { get; set; }
        public string Oaz66 { get; set; }
        public string Oaz67 { get; set; }
        public short? Oaz681 { get; set; }
        public short? Oaz682 { get; set; }
        public short? Oaz691 { get; set; }
        public short? Oaz692 { get; set; }
        public string Oaz70 { get; set; }
        public string Oaz71 { get; set; }
        public string Oaz72 { get; set; }
        public string Oaz73 { get; set; }
        public string Oaz99 { get; set; }
        public string Oaz74 { get; set; }
        public string Oaz75 { get; set; }
        public string Oaz76 { get; set; }
        public string Oaz77 { get; set; }
        public string Oaz78 { get; set; }
        public string Oaz79 { get; set; }
        public string Oaz80 { get; set; }
        public string Oaz81 { get; set; }
        public string Oaz83 { get; set; }
        public string Oaz84 { get; set; }
        public string Oaz85 { get; set; }
        public string Oaz86 { get; set; }
        public string Oaz87 { get; set; }
        public string Oaz88 { get; set; }
        public string Oaz89 { get; set; }
        public string Oaz90 { get; set; }
        public string Oaz91 { get; set; }
        public string Oazud01 { get; set; }
        public string Oazud02 { get; set; }
        public string Oazud03 { get; set; }
        public string Oazud04 { get; set; }
        public string Oazud05 { get; set; }
        public string Oazud06 { get; set; }
        public decimal? Oazud07 { get; set; }
        public decimal? Oazud08 { get; set; }
        public decimal? Oazud09 { get; set; }
        public int? Oazud10 { get; set; }
        public int? Oazud11 { get; set; }
        public int? Oazud12 { get; set; }
        public DateTime? Oazud13 { get; set; }
        public DateTime? Oazud14 { get; set; }
        public DateTime? Oazud15 { get; set; }
    }
}
