using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OccaFile
    {
        public string Occa00 { get; set; }
        public string Occano { get; set; }
        public string Occa011 { get; set; }
        public string Occa01 { get; set; }
        public string Occa02 { get; set; }
        public string Occa03 { get; set; }
        public string Occa04 { get; set; }
        public string Occa05 { get; set; }
        public string Occa06 { get; set; }
        public string Occa07 { get; set; }
        public string Occa08 { get; set; }
        public string Occa09 { get; set; }
        public string Occa10 { get; set; }
        public string Occa11 { get; set; }
        public DateTime? Occa12 { get; set; }
        public decimal? Occa13 { get; set; }
        public decimal? Occa14 { get; set; }
        public long? Occa15 { get; set; }
        public DateTime? Occa16 { get; set; }
        public DateTime? Occa171 { get; set; }
        public DateTime? Occa172 { get; set; }
        public DateTime? Occa173 { get; set; }
        public DateTime? Occa174 { get; set; }
        public DateTime? Occa175 { get; set; }
        public string Occa18 { get; set; }
        public string Occa19 { get; set; }
        public string Occa20 { get; set; }
        public string Occa21 { get; set; }
        public string Occa22 { get; set; }
        public string Occa231 { get; set; }
        public string Occa232 { get; set; }
        public string Occa233 { get; set; }
        public string Occa241 { get; set; }
        public string Occa242 { get; set; }
        public string Occa243 { get; set; }
        public string Occa261 { get; set; }
        public string Occa262 { get; set; }
        public string Occa263 { get; set; }
        public string Occa271 { get; set; }
        public string Occa272 { get; set; }
        public string Occa273 { get; set; }
        public string Occa28 { get; set; }
        public string Occa29 { get; set; }
        public string Occa292 { get; set; }
        public string Occa30 { get; set; }
        public string Occa302 { get; set; }
        public string Occa31 { get; set; }
        public decimal? Occa32 { get; set; }
        public string Occa33 { get; set; }
        public string Occa34 { get; set; }
        public string Occa35 { get; set; }
        public short? Occa36 { get; set; }
        public string Occa37 { get; set; }
        public string Occa38 { get; set; }
        public string Occa39 { get; set; }
        public string Occa39a { get; set; }
        public string Occa40 { get; set; }
        public string Occa41 { get; set; }
        public string Occa42 { get; set; }
        public string Occa43 { get; set; }
        public string Occa44 { get; set; }
        public string Occa45 { get; set; }
        public string Occa46 { get; set; }
        public string Occa47 { get; set; }
        public string Occa48 { get; set; }
        public string Occa49 { get; set; }
        public string Occa50 { get; set; }
        public string Occa51 { get; set; }
        public string Occa52 { get; set; }
        public short? Occa53 { get; set; }
        public string Occa55 { get; set; }
        public string Occa56 { get; set; }
        public string Occa57 { get; set; }
        public string Occa61 { get; set; }
        public string Occa62 { get; set; }
        public decimal? Occa63 { get; set; }
        public string Occa631 { get; set; }
        public short? Occa64 { get; set; }
        public string Occa701 { get; set; }
        public string Occa702 { get; set; }
        public string Occa703 { get; set; }
        public string Occa704 { get; set; }
        public string Occaacti { get; set; }
        public string Occauser { get; set; }
        public string Occagrup { get; set; }
        public string Occamodu { get; set; }
        public DateTime? Occadate { get; set; }
        public string Occa65 { get; set; }
        public DateTime? Occa1001 { get; set; }
        public DateTime? Occa1002 { get; set; }
        public string Occa1003 { get; set; }
        public string Occa1004 { get; set; }
        public string Occa1005 { get; set; }
        public string Occa1006 { get; set; }
        public string Occa1007 { get; set; }
        public string Occa1008 { get; set; }
        public string Occa1009 { get; set; }
        public string Occa1010 { get; set; }
        public string Occa1011 { get; set; }
        public string Occa1012 { get; set; }
        public string Occa1013 { get; set; }
        public string Occa1014 { get; set; }
        public DateTime? Occa1015 { get; set; }
        public string Occa1016 { get; set; }
        public string Occa1017 { get; set; }
        public DateTime? Occa1018 { get; set; }
        public DateTime? Occa1019 { get; set; }
        public string Occa1020 { get; set; }
        public string Occa1021 { get; set; }
        public string Occa1022 { get; set; }
        public string Occa1023 { get; set; }
        public string Occa1024 { get; set; }
        public string Occa1025 { get; set; }
        public short? Occa1026 { get; set; }
        public string Occa1027 { get; set; }
        public decimal? Occa1028 { get; set; }
        public string Occaud01 { get; set; }
        public string Occaud02 { get; set; }
        public string Occaud03 { get; set; }
        public string Occaud04 { get; set; }
        public string Occaud05 { get; set; }
        public string Occaud06 { get; set; }
        public decimal? Occaud07 { get; set; }
        public decimal? Occaud08 { get; set; }
        public decimal? Occaud09 { get; set; }
        public int? Occaud10 { get; set; }
        public int? Occaud11 { get; set; }
        public int? Occaud12 { get; set; }
        public DateTime? Occaud13 { get; set; }
        public DateTime? Occaud14 { get; set; }
        public DateTime? Occaud15 { get; set; }
        public string Occa66 { get; set; }
        public string Occa1029 { get; set; }
        public string Occa67 { get; set; }
        public string Occaoriu { get; set; }
        public string Occaorig { get; set; }
        public string Occa68 { get; set; }
        public string Occa69 { get; set; }
    }
}
