using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OccFile
    {
        public string Occ01 { get; set; }
        public string Occ02 { get; set; }
        public string Occ03 { get; set; }
        public string Occ04 { get; set; }
        public string Occ05 { get; set; }
        public string Occ06 { get; set; }
        public string Occ07 { get; set; }
        public string Occ08 { get; set; }
        public string Occ09 { get; set; }
        public string Occ10 { get; set; }
        public string Occ11 { get; set; }
        public DateTime? Occ12 { get; set; }
        public decimal? Occ13 { get; set; }
        public decimal? Occ14 { get; set; }
        public long? Occ15 { get; set; }
        public DateTime? Occ16 { get; set; }
        public DateTime? Occ171 { get; set; }
        public DateTime? Occ172 { get; set; }
        public DateTime? Occ173 { get; set; }
        public DateTime? Occ174 { get; set; }
        public DateTime? Occ175 { get; set; }
        public string Occ18 { get; set; }
        public string Occ19 { get; set; }
        public string Occ20 { get; set; }
        public string Occ21 { get; set; }
        public string Occ22 { get; set; }
        public string Occ231 { get; set; }
        public string Occ232 { get; set; }
        public string Occ233 { get; set; }
        public string Occ241 { get; set; }
        public string Occ242 { get; set; }
        public string Occ243 { get; set; }
        public string Occ261 { get; set; }
        public string Occ262 { get; set; }
        public string Occ263 { get; set; }
        public string Occ271 { get; set; }
        public string Occ272 { get; set; }
        public string Occ273 { get; set; }
        public string Occ28 { get; set; }
        public string Occ29 { get; set; }
        public string Occ292 { get; set; }
        public string Occ30 { get; set; }
        public string Occ302 { get; set; }
        public string Occ31 { get; set; }
        public decimal? Occ32 { get; set; }
        public string Occ33 { get; set; }
        public string Occ34 { get; set; }
        public string Occ35 { get; set; }
        public short? Occ36 { get; set; }
        public string Occ37 { get; set; }
        public string Occ38 { get; set; }
        public string Occ39 { get; set; }
        public string Occ39a { get; set; }
        public string Occ40 { get; set; }
        public string Occ41 { get; set; }
        public string Occ42 { get; set; }
        public string Occ43 { get; set; }
        public string Occ44 { get; set; }
        public string Occ45 { get; set; }
        public string Occ46 { get; set; }
        public string Occ47 { get; set; }
        public string Occ48 { get; set; }
        public string Occ49 { get; set; }
        public string Occ50 { get; set; }
        public string Occ51 { get; set; }
        public string Occ52 { get; set; }
        public short? Occ53 { get; set; }
        public string Occ55 { get; set; }
        public string Occ56 { get; set; }
        public string Occ57 { get; set; }
        public string Occ61 { get; set; }
        public string Occ62 { get; set; }
        public decimal? Occ63 { get; set; }
        public string Occ631 { get; set; }
        public short? Occ64 { get; set; }
        public string Occ701 { get; set; }
        public string Occ702 { get; set; }
        public string Occ703 { get; set; }
        public string Occ704 { get; set; }
        public string Occacti { get; set; }
        public string Occuser { get; set; }
        public string Occgrup { get; set; }
        public string Occmodu { get; set; }
        public DateTime? Occdate { get; set; }
        public string Occ65 { get; set; }
        public DateTime? Occ1001 { get; set; }
        public DateTime? Occ1002 { get; set; }
        public string Occ1003 { get; set; }
        public string Occ1004 { get; set; }
        public string Occ1005 { get; set; }
        public string Occ1006 { get; set; }
        public string Occ1007 { get; set; }
        public string Occ1008 { get; set; }
        public string Occ1009 { get; set; }
        public string Occ1010 { get; set; }
        public string Occ1011 { get; set; }
        public string Occ1012 { get; set; }
        public string Occ1013 { get; set; }
        public string Occ1014 { get; set; }
        public DateTime? Occ1015 { get; set; }
        public string Occ1016 { get; set; }
        public string Occ1017 { get; set; }
        public DateTime? Occ1018 { get; set; }
        public DateTime? Occ1019 { get; set; }
        public string Occ1020 { get; set; }
        public string Occ1021 { get; set; }
        public string Occ1022 { get; set; }
        public string Occ1023 { get; set; }
        public string Occ1024 { get; set; }
        public string Occ1025 { get; set; }
        public short? Occ1026 { get; set; }
        public string Occ1027 { get; set; }
        public decimal? Occ1028 { get; set; }
        public string Occud01 { get; set; }
        public string Occud02 { get; set; }
        public string Occud03 { get; set; }
        public string Occud04 { get; set; }
        public string Occud05 { get; set; }
        public string Occud06 { get; set; }
        public decimal? Occud07 { get; set; }
        public decimal? Occud08 { get; set; }
        public decimal? Occud09 { get; set; }
        public int? Occud10 { get; set; }
        public int? Occud11 { get; set; }
        public int? Occud12 { get; set; }
        public DateTime? Occud13 { get; set; }
        public DateTime? Occud14 { get; set; }
        public DateTime? Occud15 { get; set; }
        public string Occ66 { get; set; }
        public string Occ1029 { get; set; }
        public string Occ67 { get; set; }
        public string Occ1705 { get; set; }
        public string Occ1706 { get; set; }
        public string Occ1707 { get; set; }
        public string Occ1708 { get; set; }
        public string Occ234 { get; set; }
        public string Occ235 { get; set; }
        public string Occ244 { get; set; }
        public string Occ245 { get; set; }
        public string Occ246 { get; set; }
        public int? Occ247 { get; set; }
        public int? Occ248 { get; set; }
        public string Occ68 { get; set; }
        public string Occ69 { get; set; }
        public string Occ71 { get; set; }
        public decimal? Occ72 { get; set; }
        public string Occ930 { get; set; }
        public string Occpos { get; set; }
        public string Occoriu { get; set; }
        public string Occorig { get; set; }
        public string Occ73 { get; set; }
        public string Occ74 { get; set; }
        public string Occ75 { get; set; }
        public string TaOcc0001 { get; set; }
    }
}
