using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OeaFile
    {
        public string Oea00 { get; set; }
        public string Oea01 { get; set; }
        public DateTime? Oea02 { get; set; }
        public string Oea03 { get; set; }
        public string Oea032 { get; set; }
        public string Oea033 { get; set; }
        public string Oea04 { get; set; }
        public string Oea044 { get; set; }
        public string Oea05 { get; set; }
        public short? Oea06 { get; set; }
        public string Oea07 { get; set; }
        public string Oea08 { get; set; }
        public short Oea09 { get; set; }
        public string Oea10 { get; set; }
        public string Oea11 { get; set; }
        public string Oea12 { get; set; }
        public string Oea14 { get; set; }
        public string Oea15 { get; set; }
        public short? Oea161 { get; set; }
        public short? Oea162 { get; set; }
        public short? Oea163 { get; set; }
        public string Oea17 { get; set; }
        public string Oea18 { get; set; }
        public string Oea19 { get; set; }
        public string Oea20 { get; set; }
        public string Oea21 { get; set; }
        public decimal? Oea211 { get; set; }
        public string Oea212 { get; set; }
        public string Oea213 { get; set; }
        public string Oea23 { get; set; }
        public decimal? Oea24 { get; set; }
        public string Oea25 { get; set; }
        public string Oea26 { get; set; }
        public string Oea27 { get; set; }
        public string Oea28 { get; set; }
        public string Oea29 { get; set; }
        public string Oea30 { get; set; }
        public string Oea31 { get; set; }
        public string Oea32 { get; set; }
        public string Oea33 { get; set; }
        public decimal? Oea34 { get; set; }
        public string Oea35 { get; set; }
        public string Oea36 { get; set; }
        public string Oea37 { get; set; }
        public string Oea38 { get; set; }
        public string Oea39 { get; set; }
        public string Oea40 { get; set; }
        public string Oea41 { get; set; }
        public string Oea42 { get; set; }
        public string Oea43 { get; set; }
        public string Oea44 { get; set; }
        public string Oea45 { get; set; }
        public string Oea46 { get; set; }
        public string Oea47 { get; set; }
        public string Oea48 { get; set; }
        public string Oea49 { get; set; }
        public string Oea50 { get; set; }
        public string Oea51 { get; set; }
        public DateTime? Oea52 { get; set; }
        public decimal? Oea53 { get; set; }
        public decimal? Oea54 { get; set; }
        public decimal? Oea55 { get; set; }
        public string Oea56 { get; set; }
        public string Oea57 { get; set; }
        public string Oea58 { get; set; }
        public DateTime? Oea59 { get; set; }
        public decimal Oea61 { get; set; }
        public decimal Oea62 { get; set; }
        public decimal Oea63 { get; set; }
        public string Oea71 { get; set; }
        public DateTime? Oea72 { get; set; }
        public string Oea99 { get; set; }
        public string Oea901 { get; set; }
        public string Oea902 { get; set; }
        public string Oea903 { get; set; }
        public string Oea904 { get; set; }
        public string Oea905 { get; set; }
        public string Oea906 { get; set; }
        public string Oea907 { get; set; }
        public DateTime? Oea908 { get; set; }
        public string Oea909 { get; set; }
        public string Oea911 { get; set; }
        public string Oea912 { get; set; }
        public string Oea913 { get; set; }
        public string Oea914 { get; set; }
        public string Oea915 { get; set; }
        public string Oea916 { get; set; }
        public string Oeamksg { get; set; }
        public string Oeasign { get; set; }
        public short? Oeadays { get; set; }
        public short? Oeaprit { get; set; }
        public short? Oeasseq { get; set; }
        public short? Oeasmax { get; set; }
        public string Oeahold { get; set; }
        public string Oeaconf { get; set; }
        public short? Oeaprsw { get; set; }
        public string Oeauser { get; set; }
        public string Oeagrup { get; set; }
        public string Oeamodu { get; set; }
        public DateTime? Oeadate { get; set; }
        public string Oeaud01 { get; set; }
        public string Oeaud02 { get; set; }
        public string Oeaud03 { get; set; }
        public string Oeaud04 { get; set; }
        public string Oeaud05 { get; set; }
        public string Oeaud06 { get; set; }
        public decimal? Oeaud07 { get; set; }
        public decimal? Oeaud08 { get; set; }
        public decimal? Oeaud09 { get; set; }
        public int? Oeaud10 { get; set; }
        public int? Oeaud11 { get; set; }
        public int? Oeaud12 { get; set; }
        public DateTime? Oeaud13 { get; set; }
        public DateTime? Oeaud14 { get; set; }
        public DateTime? Oeaud15 { get; set; }
        public string Oea65 { get; set; }
        public string Oea1001 { get; set; }
        public string Oea1002 { get; set; }
        public string Oea1003 { get; set; }
        public string Oea1004 { get; set; }
        public string Oea1005 { get; set; }
        public decimal? Oea1006 { get; set; }
        public decimal? Oea1007 { get; set; }
        public decimal? Oea1008 { get; set; }
        public string Oea1009 { get; set; }
        public string Oea1010 { get; set; }
        public string Oea1011 { get; set; }
        public string Oea1012 { get; set; }
        public decimal? Oea1013 { get; set; }
        public decimal? Oea1014 { get; set; }
        public string Oea1015 { get; set; }
        public string Oea68 { get; set; }
        public string Oea80 { get; set; }
        public string Oea81 { get; set; }
        public string Oea82 { get; set; }
        public string Oea917 { get; set; }
        public string Oeaslk01 { get; set; }
        public string Oea918 { get; set; }
        public string Oea919 { get; set; }
        public string Oea83 { get; set; }
        public string Oea84 { get; set; }
        public string Oea85 { get; set; }
        public string Oea86 { get; set; }
        public string Oea87 { get; set; }
        public string Oea88 { get; set; }
        public string Oea89 { get; set; }
        public string Oea90 { get; set; }
        public string Oea91 { get; set; }
        public string Oea92 { get; set; }
        public string Oea93 { get; set; }
        public string Oeacont { get; set; }
        public string Oeaconu { get; set; }
        public string Oeaplant { get; set; }
        public string Oealegal { get; set; }
        public string Oeaoriu { get; set; }
        public string Oeaorig { get; set; }
        public string Oea94 { get; set; }
        public string Oeaslk02 { get; set; }
        public decimal? Oea261 { get; set; }
        public decimal? Oea262 { get; set; }
        public decimal? Oea263 { get; set; }
    }
}
