using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OebFile
    {
        public string Oeb01 { get; set; }
        public short Oeb03 { get; set; }
        public string Oeb04 { get; set; }
        public string Oeb05 { get; set; }
        public decimal Oeb05Fac { get; set; }
        public string Oeb06 { get; set; }
        public string Oeb07 { get; set; }
        public string Oeb08 { get; set; }
        public string Oeb09 { get; set; }
        public string Oeb091 { get; set; }
        public string Oeb092 { get; set; }
        public string Oeb11 { get; set; }
        public decimal Oeb12 { get; set; }
        public decimal Oeb13 { get; set; }
        public decimal Oeb14 { get; set; }
        public decimal Oeb14t { get; set; }
        public DateTime? Oeb15 { get; set; }
        public DateTime? Oeb16 { get; set; }
        public decimal? Oeb17 { get; set; }
        public string Oeb18 { get; set; }
        public string Oeb19 { get; set; }
        public string Oeb20 { get; set; }
        public string Oeb21 { get; set; }
        public string Oeb22 { get; set; }
        public decimal Oeb23 { get; set; }
        public decimal Oeb24 { get; set; }
        public decimal Oeb25 { get; set; }
        public decimal Oeb26 { get; set; }
        public string Oeb70 { get; set; }
        public DateTime? Oeb70d { get; set; }
        public string Oeb71 { get; set; }
        public DateTime? Oeb72 { get; set; }
        public decimal? Oeb901 { get; set; }
        public DateTime? Oeb902 { get; set; }
        public decimal? Oeb903 { get; set; }
        public decimal? Oeb904 { get; set; }
        public decimal? Oeb905 { get; set; }
        public string Oeb906 { get; set; }
        public string Oeb907 { get; set; }
        public string Oeb908 { get; set; }
        public string Oeb909 { get; set; }
        public string Oeb910 { get; set; }
        public decimal? Oeb911 { get; set; }
        public decimal? Oeb912 { get; set; }
        public string Oeb913 { get; set; }
        public decimal? Oeb914 { get; set; }
        public decimal? Oeb915 { get; set; }
        public string Oeb916 { get; set; }
        public decimal? Oeb917 { get; set; }
        public string Oeb1001 { get; set; }
        public string Oeb1002 { get; set; }
        public string Oeb1003 { get; set; }
        public string Oeb1004 { get; set; }
        public string Oeb1005 { get; set; }
        public decimal? Oeb1006 { get; set; }
        public string Oeb1007 { get; set; }
        public string Oeb1008 { get; set; }
        public decimal? Oeb1009 { get; set; }
        public string Oeb1010 { get; set; }
        public string Oeb1011 { get; set; }
        public string Oeb1012 { get; set; }
        public decimal? Oeb920 { get; set; }
        public decimal? Oeb1013 { get; set; }
        public string Oeb930 { get; set; }
        public string Oeb27 { get; set; }
        public decimal? Oeb28 { get; set; }
        public decimal? Oeb29 { get; set; }
        public DateTime? Oeb30 { get; set; }
        public string Oeb31 { get; set; }
        public string Oeb935 { get; set; }
        public short? Oeb936 { get; set; }
        public short? Oeb937 { get; set; }
        public string Oeb41 { get; set; }
        public string Oeb42 { get; set; }
        public string Oeb43 { get; set; }
        public string Oeb931 { get; set; }
        public decimal? Oeb932 { get; set; }
        public string Oeb933 { get; set; }
        public string Oeb934 { get; set; }
        public string Oebud01 { get; set; }
        public string Oebud02 { get; set; }
        public string Oebud03 { get; set; }
        public string Oebud04 { get; set; }
        public string Oebud05 { get; set; }
        public string Oebud06 { get; set; }
        public decimal? Oebud07 { get; set; }
        public decimal? Oebud08 { get; set; }
        public decimal? Oebud09 { get; set; }
        public int? Oebud10 { get; set; }
        public int? Oebud11 { get; set; }
        public int? Oebud12 { get; set; }
        public DateTime? Oebud13 { get; set; }
        public DateTime? Oebud14 { get; set; }
        public DateTime? Oebud15 { get; set; }
        public string Oeb44 { get; set; }
        public decimal? Oeb45 { get; set; }
        public decimal? Oeb46 { get; set; }
        public decimal Oeb47 { get; set; }
        public string Oeb48 { get; set; }
        public string Oebplant { get; set; }
        public string Oeblegal { get; set; }
        public DateTime? Oeb32 { get; set; }
        public string Oeb918 { get; set; }
        public string Oeb919 { get; set; }
        public string Oeb49 { get; set; }
        public string Oeb50 { get; set; }
        public decimal Oeb37 { get; set; }
        public string TaOeb001 { get; set; }
        public string TaOeb002 { get; set; }
        public string TaOeb003 { get; set; }
        public string TaOeb004 { get; set; }
        public string TaOeb005 { get; set; }
        public decimal? TaOeb006 { get; set; }
        public decimal? TaOeb007 { get; set; }
        public string TaOeb008 { get; set; }
        public decimal? TaOeb009 { get; set; }
        public string TaOeb010 { get; set; }
    }
}
