using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class OgaFile
    {
        public string Oga00 { get; set; }
        public string Oga01 { get; set; }
        public string Oga011 { get; set; }
        public DateTime? Oga02 { get; set; }
        public DateTime? Oga021 { get; set; }
        public DateTime? Oga022 { get; set; }
        public string Oga03 { get; set; }
        public string Oga032 { get; set; }
        public string Oga033 { get; set; }
        public string Oga04 { get; set; }
        public string Oga044 { get; set; }
        public string Oga05 { get; set; }
        public string Oga06 { get; set; }
        public string Oga07 { get; set; }
        public string Oga08 { get; set; }
        public string Oga09 { get; set; }
        public string Oga10 { get; set; }
        public DateTime? Oga11 { get; set; }
        public DateTime? Oga12 { get; set; }
        public string Oga13 { get; set; }
        public string Oga14 { get; set; }
        public string Oga15 { get; set; }
        public string Oga16 { get; set; }
        public short Oga161 { get; set; }
        public short Oga162 { get; set; }
        public short Oga163 { get; set; }
        public short? Oga17 { get; set; }
        public string Oga18 { get; set; }
        public string Oga19 { get; set; }
        public string Oga20 { get; set; }
        public string Oga21 { get; set; }
        public decimal? Oga211 { get; set; }
        public string Oga212 { get; set; }
        public string Oga213 { get; set; }
        public string Oga23 { get; set; }
        public decimal? Oga24 { get; set; }
        public string Oga25 { get; set; }
        public string Oga26 { get; set; }
        public string Oga27 { get; set; }
        public string Oga28 { get; set; }
        public decimal? Oga29 { get; set; }
        public string Oga30 { get; set; }
        public string Oga31 { get; set; }
        public string Oga32 { get; set; }
        public string Oga33 { get; set; }
        public short? Oga34 { get; set; }
        public string Oga35 { get; set; }
        public string Oga36 { get; set; }
        public string Oga37 { get; set; }
        public string Oga38 { get; set; }
        public string Oga39 { get; set; }
        public string Oga40 { get; set; }
        public string Oga41 { get; set; }
        public string Oga42 { get; set; }
        public string Oga43 { get; set; }
        public string Oga44 { get; set; }
        public string Oga45 { get; set; }
        public string Oga46 { get; set; }
        public string Oga47 { get; set; }
        public string Oga48 { get; set; }
        public DateTime? Oga49 { get; set; }
        public decimal Oga50 { get; set; }
        public decimal? Oga501 { get; set; }
        public decimal? Oga51 { get; set; }
        public decimal? Oga511 { get; set; }
        public decimal Oga52 { get; set; }
        public decimal Oga53 { get; set; }
        public decimal Oga54 { get; set; }
        public string Oga99 { get; set; }
        public string Oga901 { get; set; }
        public string Oga902 { get; set; }
        public string Oga903 { get; set; }
        public string Oga904 { get; set; }
        public string Oga905 { get; set; }
        public string Oga906 { get; set; }
        public string Oga907 { get; set; }
        public string Oga908 { get; set; }
        public string Oga909 { get; set; }
        public string Oga910 { get; set; }
        public string Oga911 { get; set; }
        public string Ogaconf { get; set; }
        public string Ogapost { get; set; }
        public short? Ogaprsw { get; set; }
        public string Ogauser { get; set; }
        public string Ogagrup { get; set; }
        public string Ogamodu { get; set; }
        public DateTime? Ogadate { get; set; }
        public string Oga55 { get; set; }
        public string Ogamksg { get; set; }
        public string Oga65 { get; set; }
        public string Oga66 { get; set; }
        public string Oga67 { get; set; }
        public string Oga1001 { get; set; }
        public string Oga1002 { get; set; }
        public string Oga1003 { get; set; }
        public string Oga1004 { get; set; }
        public string Oga1005 { get; set; }
        public decimal? Oga1006 { get; set; }
        public decimal? Oga1007 { get; set; }
        public decimal? Oga1008 { get; set; }
        public string Oga1009 { get; set; }
        public string Oga1010 { get; set; }
        public string Oga1011 { get; set; }
        public string Oga1012 { get; set; }
        public string Oga1013 { get; set; }
        public string Oga1014 { get; set; }
        public string Oga1015 { get; set; }
        public string Oga1016 { get; set; }
        public string Oga68 { get; set; }
        public string Ogaspc { get; set; }
        public DateTime? Oga69 { get; set; }
        public string Oga912 { get; set; }
        public DateTime? Oga913 { get; set; }
        public string Oga914 { get; set; }
        public string Oga70 { get; set; }
        public string Ogaud01 { get; set; }
        public string Ogaud02 { get; set; }
        public string Ogaud03 { get; set; }
        public string Ogaud04 { get; set; }
        public string Ogaud05 { get; set; }
        public string Ogaud06 { get; set; }
        public decimal? Ogaud07 { get; set; }
        public decimal? Ogaud08 { get; set; }
        public decimal? Ogaud09 { get; set; }
        public int? Ogaud10 { get; set; }
        public int? Ogaud11 { get; set; }
        public int? Ogaud12 { get; set; }
        public DateTime? Ogaud13 { get; set; }
        public DateTime? Ogaud14 { get; set; }
        public string Ogaud15 { get; set; }
        public string Oga83 { get; set; }
        public string Oga84 { get; set; }
        public string Oga85 { get; set; }
        public string Oga86 { get; set; }
        public string Oga87 { get; set; }
        public string Oga88 { get; set; }
        public string Oga89 { get; set; }
        public string Oga90 { get; set; }
        public string Oga91 { get; set; }
        public string Oga92 { get; set; }
        public string Oga93 { get; set; }
        public string Oga94 { get; set; }
        public short? Oga95 { get; set; }
        public string Oga96 { get; set; }
        public short? Oga97 { get; set; }
        public DateTime? Ogacond { get; set; }
        public string Ogaconu { get; set; }
        public string Ogaplant { get; set; }
        public string Ogalegal { get; set; }
        public string Oga71 { get; set; }
        public string Ogaoriu { get; set; }
        public string Ogaorig { get; set; }
        public string Ogacont { get; set; }
        public string Oga98 { get; set; }
        public DateTime? Oga72 { get; set; }
        public string Oga57 { get; set; }
        public string TaOga1017 { get; set; }
        public string TaOga1018 { get; set; }
        public string TaOga1019 { get; set; }
        public string TaOga1020 { get; set; }
        public string TaOga1021 { get; set; }
        public string TaOga1022 { get; set; }
        public string TaOga1023 { get; set; }
        public string TaOga1024 { get; set; }
        public string TaOga1025 { get; set; }
        public string TaOga1026 { get; set; }
    }
}
