using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class PmcFile
    {
        public string Pmc01 { get; set; }
        public string Pmc02 { get; set; }
        public string Pmc03 { get; set; }
        public string Pmc04 { get; set; }
        public string Pmc05 { get; set; }
        public string Pmc06 { get; set; }
        public string Pmc07 { get; set; }
        public string Pmc081 { get; set; }
        public string Pmc082 { get; set; }
        public string Pmc091 { get; set; }
        public string Pmc092 { get; set; }
        public string Pmc093 { get; set; }
        public string Pmc094 { get; set; }
        public string Pmc095 { get; set; }
        public string Pmc10 { get; set; }
        public string Pmc11 { get; set; }
        public string Pmc12 { get; set; }
        public string Pmc13 { get; set; }
        public string Pmc14 { get; set; }
        public string Pmc15 { get; set; }
        public string Pmc16 { get; set; }
        public string Pmc17 { get; set; }
        public string Pmc18 { get; set; }
        public string Pmc19 { get; set; }
        public string Pmc20 { get; set; }
        public string Pmc21 { get; set; }
        public string Pmc22 { get; set; }
        public string Pmc23 { get; set; }
        public string Pmc24 { get; set; }
        public string Pmc25 { get; set; }
        public string Pmc26 { get; set; }
        public string Pmc27 { get; set; }
        public short? Pmc28 { get; set; }
        public string Pmc30 { get; set; }
        public DateTime? Pmc40 { get; set; }
        public DateTime? Pmc41 { get; set; }
        public DateTime? Pmc42 { get; set; }
        public DateTime? Pmc43 { get; set; }
        public DateTime? Pmc44 { get; set; }
        public decimal? Pmc45 { get; set; }
        public decimal? Pmc46 { get; set; }
        public string Pmc47 { get; set; }
        public string Pmc48 { get; set; }
        public string Pmc49 { get; set; }
        public short? Pmc50 { get; set; }
        public short? Pmc51 { get; set; }
        public string Pmc52 { get; set; }
        public string Pmc53 { get; set; }
        public string Pmc54 { get; set; }
        public string Pmc55 { get; set; }
        public string Pmc56 { get; set; }
        public string Pmc901 { get; set; }
        public string Pmc902 { get; set; }
        public string Pmc903 { get; set; }
        public string Pmc904 { get; set; }
        public string Pmc905 { get; set; }
        public string Pmc906 { get; set; }
        public string Pmc907 { get; set; }
        public string Pmc908 { get; set; }
        public string Pmc909 { get; set; }
        public string Pmc910 { get; set; }
        public string Pmc911 { get; set; }
        public string Pmcacti { get; set; }
        public string Pmcuser { get; set; }
        public string Pmcgrup { get; set; }
        public string Pmcmodu { get; set; }
        public DateTime? Pmcdate { get; set; }
        public string Pmcud01 { get; set; }
        public string Pmcud02 { get; set; }
        public string Pmcud03 { get; set; }
        public string Pmcud04 { get; set; }
        public string Pmcud05 { get; set; }
        public string Pmcud06 { get; set; }
        public decimal? Pmcud07 { get; set; }
        public decimal? Pmcud08 { get; set; }
        public string Pmcud09 { get; set; }
        public string Pmcud10 { get; set; }
        public int? Pmcud11 { get; set; }
        public int? Pmcud12 { get; set; }
        public DateTime? Pmcud13 { get; set; }
        public DateTime? Pmcud14 { get; set; }
        public DateTime? Pmcud15 { get; set; }
        public string Pmc912 { get; set; }
        public string Pmc1912 { get; set; }
        public string Pmc1913 { get; set; }
        public string Pmc1914 { get; set; }
        public string Pmc1915 { get; set; }
        public string Pmc1916 { get; set; }
        public string Pmc1917 { get; set; }
        public decimal? Pmc1918 { get; set; }
        public string Pmc1919 { get; set; }
        public string Pmc1920 { get; set; }
        public int? Pmc1921 { get; set; }
        public string Pmc913 { get; set; }
        public string Pmc281 { get; set; }
        public string Pmc914 { get; set; }
        public string Pmc915 { get; set; }
        public string Pmc916 { get; set; }
        public string Pmc917 { get; set; }
        public string Pmc918 { get; set; }
        public string Pmc919 { get; set; }
        public string Pmc920 { get; set; }
        public string Pmc921 { get; set; }
        public string Pmc922 { get; set; }
        public string Pmc923 { get; set; }
        public string Pmc57 { get; set; }
        public short? Pmc58 { get; set; }
        public string Pmc59 { get; set; }
        public string Pmc60 { get; set; }
        public string Pmc930 { get; set; }
        public DateTime? Pmccrat { get; set; }
        public string Pmcoriu { get; set; }
        public string Pmcorig { get; set; }
        public short? Pmc29 { get; set; }
        public string TaPmc001 { get; set; }
        public string TaPmc002 { get; set; }
        public string TaPmc003 { get; set; }
        public string TaPmc004 { get; set; }
        public string TaPmc005 { get; set; }
        public string TaPmc006 { get; set; }
        public string TaPmc007 { get; set; }
        public string TaPmc008 { get; set; }
        public string TaPmc009 { get; set; }
    }
}
