using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class SfbFile
    {
        public string Sfb01 { get; set; }
        public short? Sfb02 { get; set; }
        public string Sfb03 { get; set; }
        public string Sfb04 { get; set; }
        public string Sfb05 { get; set; }
        public string Sfb06 { get; set; }
        public string Sfb07 { get; set; }
        public DateTime? Sfb071 { get; set; }
        public decimal Sfb08 { get; set; }
        public decimal Sfb081 { get; set; }
        public decimal Sfb09 { get; set; }
        public decimal Sfb10 { get; set; }
        public decimal Sfb11 { get; set; }
        public decimal Sfb111 { get; set; }
        public decimal Sfb12 { get; set; }
        public decimal? Sfb121 { get; set; }
        public decimal? Sfb122 { get; set; }
        public DateTime? Sfb13 { get; set; }
        public string Sfb14 { get; set; }
        public DateTime? Sfb15 { get; set; }
        public string Sfb16 { get; set; }
        public short? Sfb17 { get; set; }
        public DateTime? Sfb18 { get; set; }
        public string Sfb19 { get; set; }
        public DateTime? Sfb20 { get; set; }
        public string Sfb21 { get; set; }
        public string Sfb22 { get; set; }
        public short? Sfb221 { get; set; }
        public string Sfb222 { get; set; }
        public string Sfb23 { get; set; }
        public string Sfb24 { get; set; }
        public DateTime? Sfb25 { get; set; }
        public DateTime? Sfb251 { get; set; }
        public string Sfb26 { get; set; }
        public string Sfb27 { get; set; }
        public string Sfb271 { get; set; }
        public string Sfb28 { get; set; }
        public string Sfb29 { get; set; }
        public string Sfb30 { get; set; }
        public string Sfb31 { get; set; }
        public string Sfb32 { get; set; }
        public string Sfb33 { get; set; }
        public decimal? Sfb34 { get; set; }
        public string Sfb35 { get; set; }
        public DateTime? Sfb36 { get; set; }
        public DateTime? Sfb37 { get; set; }
        public DateTime? Sfb38 { get; set; }
        public string Sfb39 { get; set; }
        public short? Sfb40 { get; set; }
        public string Sfb41 { get; set; }
        public short? Sfb42 { get; set; }
        public DateTime? Sfb81 { get; set; }
        public string Sfb82 { get; set; }
        public string Sfb85 { get; set; }
        public string Sfb86 { get; set; }
        public string Sfb87 { get; set; }
        public string Sfb88 { get; set; }
        public string Sfb91 { get; set; }
        public short? Sfb92 { get; set; }
        public string Sfb93 { get; set; }
        public string Sfb94 { get; set; }
        public string Sfb95 { get; set; }
        public string Sfb96 { get; set; }
        public string Sfb97 { get; set; }
        public string Sfb98 { get; set; }
        public string Sfb99 { get; set; }
        public string Sfb100 { get; set; }
        public short? Sfb101 { get; set; }
        public string Sfbacti { get; set; }
        public string Sfbuser { get; set; }
        public string Sfbgrup { get; set; }
        public string Sfbmodu { get; set; }
        public DateTime? Sfbdate { get; set; }
        public string Sfb1001 { get; set; }
        public string Sfb1002 { get; set; }
        public string Sfb1003 { get; set; }
        public string Sfb102 { get; set; }
        public string Sfb50 { get; set; }
        public string Sfb51 { get; set; }
        public short? Sfb103 { get; set; }
        public string Sfbud01 { get; set; }
        public string Sfbud02 { get; set; }
        public string Sfbud03 { get; set; }
        public string Sfbud04 { get; set; }
        public string Sfbud05 { get; set; }
        public string Sfbud06 { get; set; }
        public string Sfbud07 { get; set; }
        public string Sfbud08 { get; set; }
        public decimal? Sfbud09 { get; set; }
        public int? Sfbud10 { get; set; }
        public int? Sfbud11 { get; set; }
        public int? Sfbud12 { get; set; }
        public DateTime? Sfbud13 { get; set; }
        public DateTime? Sfbud14 { get; set; }
        public DateTime? Sfbud15 { get; set; }
        public string Sfb43 { get; set; }
        public string Sfb44 { get; set; }
        public string Sfbmksg { get; set; }
        public string Sfbplant { get; set; }
        public string Sfblegal { get; set; }
        public string Sfboriu { get; set; }
        public string Sfborig { get; set; }
        public string Sfb104 { get; set; }
        public string Sfb919 { get; set; }
        public decimal? TaSfb001 { get; set; }
        public decimal? TaSfb002 { get; set; }
        public string TaSfb003 { get; set; }
        public string TaSfb004 { get; set; }
        public string TaSfb005 { get; set; }
        public string TaSfb006 { get; set; }
        public string TaSfb007 { get; set; }
        public string TaSfb008 { get; set; }
        public decimal? TaSfb009 { get; set; }
        public decimal? TaSfb010 { get; set; }
        public string TaSfb011 { get; set; }
        public string TaSfb012 { get; set; }
    }
}
