using System;
using System.Collections.Generic;

#nullable disable

namespace APEX_API.TopprodModels
{
    public partial class SmaFile
    {
        public string Sma00 { get; set; }
        public string Sma01 { get; set; }
        public string Sma02 { get; set; }
        public string Sma03 { get; set; }
        public string Sma04 { get; set; }
        public string Sma05 { get; set; }
        public string Sma06 { get; set; }
        public string Sma07 { get; set; }
        public string Sma08 { get; set; }
        public string Sma09 { get; set; }
        public string Sma10 { get; set; }
        public string Sma11 { get; set; }
        public string Sma12 { get; set; }
        public decimal? Sma13 { get; set; }
        public decimal? Sma14 { get; set; }
        public short? Sma15 { get; set; }
        public short? Sma16 { get; set; }
        public short? Sma17 { get; set; }
        public string Sma18 { get; set; }
        public short? Sma19 { get; set; }
        public short? Sma20 { get; set; }
        public DateTime? Sma21 { get; set; }
        public string Sma22 { get; set; }
        public string Sma23 { get; set; }
        public string Sma24 { get; set; }
        public string Sma25 { get; set; }
        public string Sma26 { get; set; }
        public string Sma27 { get; set; }
        public string Sma28 { get; set; }
        public string Sma29 { get; set; }
        public DateTime? Sma30 { get; set; }
        public string Sma31 { get; set; }
        public string Sma32 { get; set; }
        public string Sma33 { get; set; }
        public decimal? Sma341 { get; set; }
        public decimal? Sma342 { get; set; }
        public decimal? Sma343 { get; set; }
        public decimal? Sma351 { get; set; }
        public decimal? Sma352 { get; set; }
        public decimal? Sma353 { get; set; }
        public string Sma36 { get; set; }
        public decimal? Sma37 { get; set; }
        public string Sma38 { get; set; }
        public string Sma39 { get; set; }
        public decimal? Sma401 { get; set; }
        public decimal? Sma402 { get; set; }
        public decimal? Sma403 { get; set; }
        public string Sma41 { get; set; }
        public string Sma42 { get; set; }
        public string Sma43 { get; set; }
        public string Sma44 { get; set; }
        public string Sma45 { get; set; }
        public string Sma46 { get; set; }
        public string Sma47 { get; set; }
        public short? Sma48 { get; set; }
        public string Sma49 { get; set; }
        public string Sma50 { get; set; }
        public short? Sma51 { get; set; }
        public short? Sma52 { get; set; }
        public DateTime? Sma53 { get; set; }
        public string Sma54 { get; set; }
        public string Sma55 { get; set; }
        public short? Sma551 { get; set; }
        public string Sma56 { get; set; }
        public string Sma57 { get; set; }
        public string Sma58 { get; set; }
        public string Sma59 { get; set; }
        public string Sma60 { get; set; }
        public short? Sma601 { get; set; }
        public short? Sma602 { get; set; }
        public short? Sma603 { get; set; }
        public short? Sma604 { get; set; }
        public short? Sma605 { get; set; }
        public string Sma609 { get; set; }
        public string Sma61 { get; set; }
        public string Sma62 { get; set; }
        public string Sma63 { get; set; }
        public string Sma64 { get; set; }
        public string Sma65 { get; set; }
        public string Sma66 { get; set; }
        public string Sma67 { get; set; }
        public decimal? Sma68 { get; set; }
        public decimal? Sma69 { get; set; }
        public string Sma70 { get; set; }
        public string Sma71 { get; set; }
        public string Sma72 { get; set; }
        public string Sma73 { get; set; }
        public decimal? Sma74 { get; set; }
        public string Sma75 { get; set; }
        public string Sma76 { get; set; }
        public string Sma77 { get; set; }
        public string Sma78 { get; set; }
        public string Sma79 { get; set; }
        public string Sma80 { get; set; }
        public string Sma81 { get; set; }
        public string Sma82 { get; set; }
        public string Sma83 { get; set; }
        public decimal? Sma84 { get; set; }
        public string Sma841 { get; set; }
        public string Sma842 { get; set; }
        public string Sma843 { get; set; }
        public string Sma844 { get; set; }
        public string Sma845 { get; set; }
        public string Sma846 { get; set; }
        public string Sma847 { get; set; }
        public string Sma848 { get; set; }
        public short? Sma849 { get; set; }
        public string Sma85 { get; set; }
        public string Sma86 { get; set; }
        public string Sma87 { get; set; }
        public string Sma88 { get; set; }
        public string Sma881 { get; set; }
        public string Sma882 { get; set; }
        public string Sma883 { get; set; }
        public string Sma884 { get; set; }
        public string Sma885 { get; set; }
        public string Sma886 { get; set; }
        public string Sma887 { get; set; }
        public string Sma888 { get; set; }
        public string Sma889 { get; set; }
        public string Sma89 { get; set; }
        public string Sma891 { get; set; }
        public string Sma892 { get; set; }
        public string Sma893 { get; set; }
        public string Sma894 { get; set; }
        public string Sma895 { get; set; }
        public string Sma896 { get; set; }
        public string Sma897 { get; set; }
        public string Sma898 { get; set; }
        public string Sma899 { get; set; }
        public string Sma901 { get; set; }
        public string Sma902 { get; set; }
        public string Sma903 { get; set; }
        public string Sma904 { get; set; }
        public string Sma905 { get; set; }
        public string Sma906 { get; set; }
        public string Sma907 { get; set; }
        public string Sma908 { get; set; }
        public string Sma909 { get; set; }
        public string Sma100 { get; set; }
        public string Sma101 { get; set; }
        public string Sma102 { get; set; }
        public string Sma103 { get; set; }
        public string Sma104 { get; set; }
        public string Sma105 { get; set; }
        public string Sma106 { get; set; }
        public string Sma107 { get; set; }
        public string Sma108 { get; set; }
        public string Sma109 { get; set; }
        public short? Sma110 { get; set; }
        public string Sma111 { get; set; }
        public string Sma112 { get; set; }
        public string Sma113 { get; set; }
        public string Sma114 { get; set; }
        public string Sma115 { get; set; }
        public string Sma116 { get; set; }
        public string Sma117 { get; set; }
        public string Sma118 { get; set; }
        public string Sma119 { get; set; }
        public string Sma120 { get; set; }
        public string Smauser { get; set; }
        public string Smagrup { get; set; }
        public string Smamodu { get; set; }
        public DateTime? Smadate { get; set; }
        public string Smaacti { get; set; }
        public string Sma121 { get; set; }
        public string Sma122 { get; set; }
        public string Sma123 { get; set; }
        public string Sma124 { get; set; }
        public string Sma910 { get; set; }
        public string Sma911 { get; set; }
        public string Sma912 { get; set; }
        public string Sma913 { get; set; }
        public short? Sma914 { get; set; }
        public decimal? Sma915 { get; set; }
        public string Sma125 { get; set; }
        public string Sma126 { get; set; }
        public string Sma127 { get; set; }
        public string Sma128 { get; set; }
        public string Sma916 { get; set; }
        public string Sma90 { get; set; }
        public bool? Sma917 { get; set; }
        public string Sma129 { get; set; }
        public string Sma130 { get; set; }
        public string Sma131 { get; set; }
        public string Sma139 { get; set; }
        public string Sma132 { get; set; }
        public decimal? Sma133 { get; set; }
        public short? Sma134 { get; set; }
        public string Sma135 { get; set; }
        public string Sma136 { get; set; }
        public short? Sma137 { get; set; }
        public string Sma138 { get; set; }
        public string Smaorig { get; set; }
        public string Smaoriu { get; set; }
        public string Sma140 { get; set; }
        public string Sma141 { get; set; }
        public string Sma541 { get; set; }
        public string Sma542 { get; set; }
        public string Sma1421 { get; set; }
        public string Sma1422 { get; set; }
        public string Sma1423 { get; set; }
        public string Sma1424 { get; set; }
        public string Sma1431 { get; set; }
        public string Sma1432 { get; set; }
        public string Sma1433 { get; set; }
        public string Sma1434 { get; set; }
        public string Sma1435 { get; set; }
        public string Sma142 { get; set; }
        public string Sma143 { get; set; }
        public string Sma144 { get; set; }
        public string Sma145 { get; set; }
        public string Sma91 { get; set; }
        public string Sma92 { get; set; }
        public string Sma1411 { get; set; }
        public string Smaud01 { get; set; }
        public string Smaud02 { get; set; }
        public string Smaud03 { get; set; }
        public string Smaud04 { get; set; }
        public string Smaud05 { get; set; }
        public string Smaud06 { get; set; }
        public decimal? Smaud07 { get; set; }
        public decimal? Smaud08 { get; set; }
        public decimal? Smaud09 { get; set; }
        public int? Smaud10 { get; set; }
        public int? Smaud11 { get; set; }
        public int? Smaud12 { get; set; }
        public DateTime? Smaud13 { get; set; }
        public DateTime? Smaud14 { get; set; }
        public DateTime? Smaud15 { get; set; }
        public string Sma146 { get; set; }
    }
}
